/**
 * Admin-only endpoints
 * Requires admin role
 */

import { router, protectedProcedure } from "../_core/trpc";
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { getDb } from "../db";
import { counties } from "../../drizzle/schema";

export const COUNTY_SEED = [
  {
    state: "TX",
    countyName: "Travis County",
    countyCode: "48453",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://traviscad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Travis Central Appraisal District",
    assessorPhone: "(512) 834-9100",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://traviscad.org/forms/",
    formTemplateName: "Travis County ARB Appeal Form",
    // Delivery dispatcher config — portal when recipe verified, cert mail fallback.
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Travis Central Appraisal District",
    mailingAddressLine1: "850 E Anderson Ln",
    mailingAddressCity: "Austin",
    mailingAddressState: "TX",
    mailingAddressZip: "78752",
  },
  {
    state: "TX",
    countyName: "Dallas County",
    countyCode: "48113",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dallascad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Dallas Central Appraisal District",
    assessorPhone: "(214) 631-0000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dallascad.org/forms/",
    formTemplateName: "Dallas County ARB Appeal Form",
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Dallas Central Appraisal District — ARB",
    mailingAddressLine1: "2949 N Stemmons Fwy",
    mailingAddressCity: "Dallas",
    mailingAddressState: "TX",
    mailingAddressZip: "75247",
  },
  {
    state: "TX",
    countyName: "Harris County",
    countyCode: "48201",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.hcad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Harris County Appraisal District",
    assessorPhone: "(713) 207-3000",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.hcad.org/forms/",
    formTemplateName: "Harris County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Harris County Appraisal District",
    mailingAddressLine1: "13013 Northwest Fwy",
    mailingAddressCity: "Houston",
    mailingAddressState: "TX",
    mailingAddressZip: "77040",
  },
  {
    state: "IL",
    countyName: "Cook County",
    countyCode: "17031",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cookcountyassessor.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cook County Assessor",
    assessorPhone: "(312) 443-7550",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cookcountyassessor.com/forms/",
    formTemplateName: "Cook County Assessment Appeal Form",
    // Cook appeals run on a rolling township schedule; use a wide window
    // so the deadline check doesn't block valid filings. Actual township
    // deadlines are checked separately at filing time.
    filingWindowStart: "01-01",
    filingWindowEnd: "12-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Cook County Board of Review",
    mailingAddressLine1: "118 N Clark St",
    mailingAddressLine2: "Room 601",
    mailingAddressCity: "Chicago",
    mailingAddressState: "IL",
    mailingAddressZip: "60602",
  },
  {
    state: "IL",
    countyName: "DuPage County",
    countyCode: "17043",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dupagecountyassessor.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "DuPage County Assessor",
    assessorPhone: "(630) 407-6500",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dupagecountyassessor.com/forms/",
    formTemplateName: "DuPage County Assessment Appeal Form",
    // DuPage Board of Review opens after assessments are published (late
    // summer) and typically closes 30 days after each township's publication.
    filingWindowStart: "07-01",
    filingWindowEnd: "11-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "DuPage County Board of Review",
    mailingAddressLine1: "421 N County Farm Rd",
    mailingAddressCity: "Wheaton",
    mailingAddressState: "IL",
    mailingAddressZip: "60187",
  },
  {
    state: "NJ",
    countyName: "Bergen County",
    countyCode: "34003",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.bergencountynj.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Bergen County Tax Board",
    assessorPhone: "(201) 336-6400",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.bergencountynj.gov/forms/",
    formTemplateName: "Bergen County Tax Appeal Form",
    filingWindowStart: "01-15",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Bergen County Board of Taxation",
    mailingAddressLine1: "1 Bergen County Plaza",
    mailingAddressLine2: "Room 370",
    mailingAddressCity: "Hackensack",
    mailingAddressState: "NJ",
    mailingAddressZip: "07601",
  },
  {
    state: "NJ",
    countyName: "Essex County",
    countyCode: "34013",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.essexcountynj.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Essex County Tax Board",
    assessorPhone: "(973) 621-4500",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.essexcountynj.org/forms/",
    formTemplateName: "Essex County Tax Appeal Form",
    filingWindowStart: "01-15",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Essex County Board of Taxation",
    mailingAddressLine1: "50 S Clinton St",
    mailingAddressLine2: "Suite 5200",
    mailingAddressCity: "East Orange",
    mailingAddressState: "NJ",
    mailingAddressZip: "07018",
  },
  {
    state: "CT",
    countyName: "Fairfield County",
    countyCode: "09001",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://portal.ct.gov/OPM/Property-Valuation-Appeals-Board/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "CT Property Valuation Appeals Board",
    assessorPhone: "(860) 702-3000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://portal.ct.gov/OPM/forms/",
    formTemplateName: "Connecticut Property Appeal Form",
    // Connecticut has no county-level assessor — appeals run through each
    // municipality's Board of Assessment Appeals (Feb 20 filing deadline).
    // Joining the waitlist surfaces the user's town for future automation.
    preferredChannel: "unsupported",
    fallbackChannel: "unsupported",
  },
  {
    state: "WI",
    countyName: "Milwaukee County",
    countyCode: "55079",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://county.milwaukee.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Milwaukee County Assessor",
    assessorPhone: "(414) 278-4455",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://county.milwaukee.gov/forms/",
    formTemplateName: "Milwaukee County Assessment Appeal Form",
    filingWindowStart: "04-15",
    filingWindowEnd: "05-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Milwaukee County Board of Review",
    mailingAddressLine1: "901 N 9th St",
    mailingAddressLine2: "Room 309",
    mailingAddressCity: "Milwaukee",
    mailingAddressState: "WI",
    mailingAddressZip: "53233",
  },
  {
    state: "OH",
    countyName: "Cuyahoga County",
    countyCode: "39035",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cuyahogacounty.us/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cuyahoga County Auditor",
    assessorPhone: "(216) 443-7000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cuyahogacounty.us/forms/",
    formTemplateName: "Cuyahoga County Property Tax Appeal Form",
    filingWindowStart: "01-01",
    filingWindowEnd: "03-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Cuyahoga County Board of Revision",
    mailingAddressLine1: "2079 E 9th St",
    mailingAddressLine2: "2nd Floor",
    mailingAddressCity: "Cleveland",
    mailingAddressState: "OH",
    mailingAddressZip: "44115",
  },
  {
    state: "PA",
    countyName: "Philadelphia County",
    countyCode: "42101",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.phila.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Philadelphia Board of Revision of Taxes",
    assessorPhone: "(215) 686-6600",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.phila.gov/forms/",
    formTemplateName: "Philadelphia Property Tax Appeal Form",
    // Philadelphia BRT accepts market-value appeals through the first Monday of October.
    filingWindowStart: "07-01",
    filingWindowEnd: "10-07",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Philadelphia Board of Revision of Taxes",
    mailingAddressLine1: "601 Walnut St",
    mailingAddressLine2: "Suite 325 East",
    mailingAddressCity: "Philadelphia",
    mailingAddressState: "PA",
    mailingAddressZip: "19106",
  },
  {
    state: "CA",
    countyName: "Los Angeles County",
    countyCode: "06037",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://assessor.lacounty.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Los Angeles County Assessor",
    assessorPhone: "(213) 974-3211",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://assessor.lacounty.gov/forms/",
    formTemplateName: "LA County Proposition 8 Application",
    filingWindowStart: "07-02",
    filingWindowEnd: "11-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Los Angeles County Assessment Appeals Board",
    mailingAddressLine1: "500 W Temple St",
    mailingAddressLine2: "Room B-4",
    mailingAddressCity: "Los Angeles",
    mailingAddressState: "CA",
    mailingAddressZip: "90012",
  },
  {
    state: "NY",
    countyName: "New York County",
    countyCode: "36061",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www1.nyc.gov/site/finance/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "NYC Department of Finance",
    assessorPhone: "(311)",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www1.nyc.gov/site/finance/forms/",
    formTemplateName: "NYC Property Tax Appeal Form",
    // NYC deadlines differ by tax class: Class 1 (1–3 family) = March 15;
    // Class 2/3/4 = March 1. Using the latest so the window is inclusive.
    filingWindowStart: "01-15",
    filingWindowEnd: "03-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "NYC Tax Commission",
    mailingAddressLine1: "1 Centre St",
    mailingAddressLine2: "Room 936",
    mailingAddressCity: "New York",
    mailingAddressState: "NY",
    mailingAddressZip: "10007",
  },
  {
    state: "FL",
    countyName: "Miami-Dade County",
    countyCode: "12086",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.miamidade.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Miami-Dade County Property Appraiser",
    assessorPhone: "(305) 375-2905",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.miamidade.gov/forms/",
    formTemplateName: "Miami-Dade County Property Tax Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Miami-Dade County VAB",
    mailingAddressLine1: "111 NW 1st St, Suite 1720",
    mailingAddressCity: "Miami",
    mailingAddressState: "FL",
    mailingAddressZip: "33128",
  },
];

export const adminRouter = router({
  /**
   * Seed counties database (admin only)
   */
  seedCounties: protectedProcedure.mutation(async ({ ctx }) => {
    if (ctx.user?.role !== "admin") {
      throw new TRPCError({
        code: "FORBIDDEN",
        message: "Admin access required",
      });
    }

    const db = await getDb();
    if (!db) throw new Error("Database unavailable");

    try {
      let seeded = 0;
      for (const county of COUNTY_SEED) {
        // onDuplicateKeyUpdate now backfills the channel-routing fields too,
        // so adding mailing addresses for previously-portal-only counties
        // takes effect on the next admin seed run without a manual SQL
        // migration. Every field explicitly listed below is one we want to
        // treat as authoritative in this seed.
        const update: Record<string, unknown> = {
          portalUrl: county.portalUrl,
          assessorPhone: county.assessorPhone,
          hearingScheduleDays: county.hearingScheduleDays,
        };
        const mailFields = [
          "filingWindowStart",
          "filingWindowEnd",
          "preferredChannel",
          "fallbackChannel",
          "mailingAddressName",
          "mailingAddressLine1",
          "mailingAddressLine2",
          "mailingAddressCity",
          "mailingAddressState",
          "mailingAddressZip",
          "intakeEmail",
          "poaEligible",
          "onlinePortalOnly",
          "pinOnlyLogin",
        ] as const;
        for (const f of mailFields) {
          const v = (county as Record<string, unknown>)[f];
          if (v !== undefined) update[f] = v;
        }
        await db.insert(counties).values(county as any).onDuplicateKeyUpdate({
          set: update,
        });
        seeded++;
      }

      return {
        success: true,
        message: `Seeded ${seeded} counties successfully`,
        count: seeded,
      };
    } catch (error) {
      console.error("[Admin] Error seeding counties:", error);
      throw new TRPCError({
        code: "INTERNAL_SERVER_ERROR",
        message: "Failed to seed counties",
      });
    }
  }),
});
