/**
 * Admin-only endpoints
 * Requires admin role
 */

import { router, protectedProcedure } from "../_core/trpc";
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { getDb } from "../db";
import { counties } from "../../drizzle/schema";

const COUNTY_SEED = [
  {
    state: "TX",
    countyName: "Travis County",
    countyCode: "48453",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://traviscad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Travis Central Appraisal District",
    assessorPhone: "(512) 834-9100",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://traviscad.org/forms/",
    formTemplateName: "Travis County ARB Appeal Form",
    // Delivery dispatcher config — portal when recipe verified, cert mail fallback.
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Travis Central Appraisal District",
    mailingAddressLine1: "850 E Anderson Ln",
    mailingAddressCity: "Austin",
    mailingAddressState: "TX",
    mailingAddressZip: "78752",
  },
  {
    state: "TX",
    countyName: "Dallas County",
    countyCode: "48113",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dallascad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Dallas Central Appraisal District",
    assessorPhone: "(214) 631-0000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dallascad.org/forms/",
    formTemplateName: "Dallas County ARB Appeal Form",
  },
  {
    state: "TX",
    countyName: "Harris County",
    countyCode: "48201",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.hcad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Harris County Appraisal District",
    assessorPhone: "(713) 207-3000",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.hcad.org/forms/",
    formTemplateName: "Harris County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Harris County Appraisal District",
    mailingAddressLine1: "13013 Northwest Fwy",
    mailingAddressCity: "Houston",
    mailingAddressState: "TX",
    mailingAddressZip: "77040",
  },
  {
    state: "IL",
    countyName: "Cook County",
    countyCode: "17031",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cookcountyassessor.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cook County Assessor",
    assessorPhone: "(312) 443-7550",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cookcountyassessor.com/forms/",
    formTemplateName: "Cook County Assessment Appeal Form",
  },
  {
    state: "IL",
    countyName: "DuPage County",
    countyCode: "17043",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dupagecountyassessor.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "DuPage County Assessor",
    assessorPhone: "(630) 407-6500",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dupagecountyassessor.com/forms/",
    formTemplateName: "DuPage County Assessment Appeal Form",
  },
  {
    state: "NJ",
    countyName: "Bergen County",
    countyCode: "34003",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.bergencountynj.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Bergen County Tax Board",
    assessorPhone: "(201) 336-6400",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.bergencountynj.gov/forms/",
    formTemplateName: "Bergen County Tax Appeal Form",
  },
  {
    state: "NJ",
    countyName: "Essex County",
    countyCode: "34013",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.essexcountynj.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Essex County Tax Board",
    assessorPhone: "(973) 621-4500",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.essexcountynj.org/forms/",
    formTemplateName: "Essex County Tax Appeal Form",
  },
  {
    state: "CT",
    countyName: "Fairfield County",
    countyCode: "09001",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://portal.ct.gov/OPM/Property-Valuation-Appeals-Board/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "CT Property Valuation Appeals Board",
    assessorPhone: "(860) 702-3000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://portal.ct.gov/OPM/forms/",
    formTemplateName: "Connecticut Property Appeal Form",
  },
  {
    state: "WI",
    countyName: "Milwaukee County",
    countyCode: "55079",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://county.milwaukee.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Milwaukee County Assessor",
    assessorPhone: "(414) 278-4455",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://county.milwaukee.gov/forms/",
    formTemplateName: "Milwaukee County Assessment Appeal Form",
  },
  {
    state: "OH",
    countyName: "Cuyahoga County",
    countyCode: "39035",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cuyahogacounty.us/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cuyahoga County Auditor",
    assessorPhone: "(216) 443-7000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cuyahogacounty.us/forms/",
    formTemplateName: "Cuyahoga County Property Tax Appeal Form",
  },
  {
    state: "PA",
    countyName: "Philadelphia County",
    countyCode: "42101",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.phila.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Philadelphia Board of Revision of Taxes",
    assessorPhone: "(215) 686-6600",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.phila.gov/forms/",
    formTemplateName: "Philadelphia Property Tax Appeal Form",
  },
  {
    state: "CA",
    countyName: "Los Angeles County",
    countyCode: "06037",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://assessor.lacounty.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Los Angeles County Assessor",
    assessorPhone: "(213) 974-3211",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://assessor.lacounty.gov/forms/",
    formTemplateName: "LA County Proposition 8 Application",
  },
  {
    state: "NY",
    countyName: "New York County",
    countyCode: "36061",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www1.nyc.gov/site/finance/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "NYC Department of Finance",
    assessorPhone: "(311)",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www1.nyc.gov/site/finance/forms/",
    formTemplateName: "NYC Property Tax Appeal Form",
  },
  {
    state: "FL",
    countyName: "Miami-Dade County",
    countyCode: "12086",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.miamidade.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Miami-Dade County Property Appraiser",
    assessorPhone: "(305) 375-2905",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.miamidade.gov/forms/",
    formTemplateName: "Miami-Dade County Property Tax Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Miami-Dade County VAB",
    mailingAddressLine1: "111 NW 1st St, Suite 1720",
    mailingAddressCity: "Miami",
    mailingAddressState: "FL",
    mailingAddressZip: "33128",
  },
];

export const adminRouter = router({
  /**
   * Seed counties database (admin only)
   */
  seedCounties: protectedProcedure.mutation(async ({ ctx }) => {
    if (ctx.user?.role !== "admin") {
      throw new TRPCError({
        code: "FORBIDDEN",
        message: "Admin access required",
      });
    }

    const db = await getDb();
    if (!db) throw new Error("Database unavailable");

    try {
      let seeded = 0;
      for (const county of COUNTY_SEED) {
        await db.insert(counties).values(county as any).onDuplicateKeyUpdate({
          set: {
            portalUrl: county.portalUrl,
            assessorPhone: county.assessorPhone,
            hearingScheduleDays: county.hearingScheduleDays,
          },
        });
        seeded++;
      }

      return {
        success: true,
        message: `Seeded ${seeded} counties successfully`,
        count: seeded,
      };
    } catch (error) {
      console.error("[Admin] Error seeding counties:", error);
      throw new TRPCError({
        code: "INTERNAL_SERVER_ERROR",
        message: "Failed to seed counties",
      });
    }
  }),
});
