/**
 * Admin-only endpoints
 * Requires admin role
 */

import { router, protectedProcedure } from "../_core/trpc";
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { eq } from "drizzle-orm";
import { getDb } from "../db";
import { counties, filingRecipes } from "../../drizzle/schema";
import { COUNTY_SEED_EXPANSION } from "../seeds/countySeedExpansion";
import { COUNTY_SEED_PHASE3 } from "../seeds/countySeedPhase3";
import { RECIPE_SEEDS } from "../seeds/filingRecipes.seed";
import { RECIPE_SEEDS_EXPANSION } from "../seeds/filingRecipesExpansion.seed";

export const COUNTY_SEED = [
  {
    state: "TX",
    countyName: "Travis County",
    countyCode: "48453",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://traviscad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Travis Central Appraisal District",
    assessorPhone: "(512) 834-9100",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://traviscad.org/forms/",
    formTemplateName: "Travis County ARB Appeal Form",
    // Delivery dispatcher config — portal when recipe verified, cert mail fallback.
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Travis Central Appraisal District",
    mailingAddressLine1: "850 E Anderson Ln",
    mailingAddressCity: "Austin",
    mailingAddressState: "TX",
    mailingAddressZip: "78752",
  },
  {
    state: "TX",
    countyName: "Dallas County",
    countyCode: "48113",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dallascad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Dallas Central Appraisal District",
    assessorPhone: "(214) 631-0000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dallascad.org/forms/",
    formTemplateName: "Dallas County ARB Appeal Form",
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Dallas Central Appraisal District — ARB",
    mailingAddressLine1: "2949 N Stemmons Fwy",
    mailingAddressCity: "Dallas",
    mailingAddressState: "TX",
    mailingAddressZip: "75247",
  },
  {
    state: "TX",
    countyName: "Harris County",
    countyCode: "48201",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.hcad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Harris County Appraisal District",
    assessorPhone: "(713) 207-3000",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.hcad.org/forms/",
    formTemplateName: "Harris County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "03-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Harris County Appraisal District",
    mailingAddressLine1: "13013 Northwest Fwy",
    mailingAddressCity: "Houston",
    mailingAddressState: "TX",
    mailingAddressZip: "77040",
  },
  {
    state: "IL",
    countyName: "Cook County",
    countyCode: "17031",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cookcountyassessor.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cook County Assessor",
    assessorPhone: "(312) 443-7550",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cookcountyassessor.com/forms/",
    formTemplateName: "Cook County Assessment Appeal Form",
    // Cook appeals run on a rolling township schedule; use a wide window
    // so the deadline check doesn't block valid filings. Actual township
    // deadlines are checked separately at filing time.
    filingWindowStart: "01-01",
    filingWindowEnd: "12-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Cook County Board of Review",
    mailingAddressLine1: "118 N Clark St",
    mailingAddressLine2: "Room 601",
    mailingAddressCity: "Chicago",
    mailingAddressState: "IL",
    mailingAddressZip: "60602",
  },
  {
    state: "IL",
    countyName: "DuPage County",
    countyCode: "17043",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dupagecountyassessor.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "DuPage County Assessor",
    assessorPhone: "(630) 407-6500",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dupagecountyassessor.com/forms/",
    formTemplateName: "DuPage County Assessment Appeal Form",
    // DuPage Board of Review opens after assessments are published (late
    // summer) and typically closes 30 days after each township's publication.
    filingWindowStart: "07-01",
    filingWindowEnd: "11-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "DuPage County Board of Review",
    mailingAddressLine1: "421 N County Farm Rd",
    mailingAddressCity: "Wheaton",
    mailingAddressState: "IL",
    mailingAddressZip: "60187",
  },
  {
    state: "NJ",
    countyName: "Bergen County",
    countyCode: "34003",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.bergencountynj.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Bergen County Tax Board",
    assessorPhone: "(201) 336-6400",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.bergencountynj.gov/forms/",
    formTemplateName: "Bergen County Tax Appeal Form",
    filingWindowStart: "01-15",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Bergen County Board of Taxation",
    mailingAddressLine1: "1 Bergen County Plaza",
    mailingAddressLine2: "Room 370",
    mailingAddressCity: "Hackensack",
    mailingAddressState: "NJ",
    mailingAddressZip: "07601",
  },
  {
    state: "NJ",
    countyName: "Essex County",
    countyCode: "34013",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.essexcountynj.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Essex County Tax Board",
    assessorPhone: "(973) 621-4500",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.essexcountynj.org/forms/",
    formTemplateName: "Essex County Tax Appeal Form",
    filingWindowStart: "01-15",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Essex County Board of Taxation",
    mailingAddressLine1: "50 S Clinton St",
    mailingAddressLine2: "Suite 5200",
    mailingAddressCity: "East Orange",
    mailingAddressState: "NJ",
    mailingAddressZip: "07018",
  },
  {
    state: "CT",
    countyName: "Fairfield County",
    countyCode: "09001",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://portal.ct.gov/OPM/Property-Valuation-Appeals-Board/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "CT Property Valuation Appeals Board",
    assessorPhone: "(860) 702-3000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://portal.ct.gov/OPM/forms/",
    formTemplateName: "Connecticut Property Appeal Form",
    // Connecticut has no county-level assessor — appeals run through each
    // municipality's Board of Assessment Appeals (Feb 20 filing deadline).
    // Joining the waitlist surfaces the user's town for future automation.
    preferredChannel: "unsupported",
    fallbackChannel: "unsupported",
  },
  {
    state: "WI",
    countyName: "Milwaukee County",
    countyCode: "55079",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://county.milwaukee.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Milwaukee County Assessor",
    assessorPhone: "(414) 278-4455",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://county.milwaukee.gov/forms/",
    formTemplateName: "Milwaukee County Assessment Appeal Form",
    filingWindowStart: "04-15",
    filingWindowEnd: "05-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Milwaukee County Board of Review",
    mailingAddressLine1: "901 N 9th St",
    mailingAddressLine2: "Room 309",
    mailingAddressCity: "Milwaukee",
    mailingAddressState: "WI",
    mailingAddressZip: "53233",
  },
  {
    state: "OH",
    countyName: "Cuyahoga County",
    countyCode: "39035",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cuyahogacounty.us/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cuyahoga County Auditor",
    assessorPhone: "(216) 443-7000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cuyahogacounty.us/forms/",
    formTemplateName: "Cuyahoga County Property Tax Appeal Form",
    filingWindowStart: "01-01",
    filingWindowEnd: "03-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Cuyahoga County Board of Revision",
    mailingAddressLine1: "2079 E 9th St",
    mailingAddressLine2: "2nd Floor",
    mailingAddressCity: "Cleveland",
    mailingAddressState: "OH",
    mailingAddressZip: "44115",
  },
  {
    state: "PA",
    countyName: "Philadelphia County",
    countyCode: "42101",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.phila.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Philadelphia Board of Revision of Taxes",
    assessorPhone: "(215) 686-6600",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.phila.gov/forms/",
    formTemplateName: "Philadelphia Property Tax Appeal Form",
    // Philadelphia BRT accepts market-value appeals through the first Monday of October.
    filingWindowStart: "07-01",
    filingWindowEnd: "10-07",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Philadelphia Board of Revision of Taxes",
    mailingAddressLine1: "601 Walnut St",
    mailingAddressLine2: "Suite 325 East",
    mailingAddressCity: "Philadelphia",
    mailingAddressState: "PA",
    mailingAddressZip: "19106",
  },
  {
    state: "CA",
    countyName: "Los Angeles County",
    countyCode: "06037",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://assessor.lacounty.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Los Angeles County Assessor",
    assessorPhone: "(213) 974-3211",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://assessor.lacounty.gov/forms/",
    formTemplateName: "LA County Proposition 8 Application",
    filingWindowStart: "07-02",
    filingWindowEnd: "11-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Los Angeles County Assessment Appeals Board",
    mailingAddressLine1: "500 W Temple St",
    mailingAddressLine2: "Room B-4",
    mailingAddressCity: "Los Angeles",
    mailingAddressState: "CA",
    mailingAddressZip: "90012",
  },
  {
    state: "NY",
    countyName: "New York County",
    countyCode: "36061",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www1.nyc.gov/site/finance/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "NYC Department of Finance",
    assessorPhone: "(311)",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www1.nyc.gov/site/finance/forms/",
    formTemplateName: "NYC Property Tax Appeal Form",
    // NYC deadlines differ by tax class: Class 1 (1–3 family) = March 15;
    // Class 2/3/4 = March 1. Using the latest so the window is inclusive.
    filingWindowStart: "01-15",
    filingWindowEnd: "03-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "NYC Tax Commission",
    mailingAddressLine1: "1 Centre St",
    mailingAddressLine2: "Room 936",
    mailingAddressCity: "New York",
    mailingAddressState: "NY",
    mailingAddressZip: "10007",
  },
  {
    state: "FL",
    countyName: "Miami-Dade County",
    countyCode: "12086",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.miamidade.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Miami-Dade County Property Appraiser",
    assessorPhone: "(305) 375-2905",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.miamidade.gov/forms/",
    formTemplateName: "Miami-Dade County Property Tax Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 1,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Miami-Dade County VAB",
    mailingAddressLine1: "111 NW 1st St, Suite 1720",
    mailingAddressCity: "Miami",
    mailingAddressState: "FL",
    mailingAddressZip: "33128",
  },

  // ── TEXAS EXPANSION ────────────────────────────────────────────────────────
  {
    state: "TX",
    countyName: "Tarrant County",
    countyCode: "48439",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.tad.org/login",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Tarrant Appraisal District",
    assessorPhone: "(817) 284-0024",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.tad.org/forms/",
    formTemplateName: "Tarrant County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Tarrant Appraisal Review Board",
    mailingAddressLine1: "P.O. Box 185519",
    mailingAddressCity: "Fort Worth",
    mailingAddressState: "TX",
    mailingAddressZip: "76181",
  },
  {
    state: "TX",
    countyName: "Collin County",
    countyCode: "48085",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://onlineportal.collincad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Collin Central Appraisal District",
    assessorPhone: "(469) 742-9200",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://onlineportal.collincad.org/",
    formTemplateName: "Collin County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-15",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Collin Appraisal Review Board",
    mailingAddressLine1: "250 Eldorado Pkwy",
    mailingAddressCity: "McKinney",
    mailingAddressState: "TX",
    mailingAddressZip: "75069",
    intakeEmail: "collinarb@collincad.org",
  },
  {
    state: "TX",
    countyName: "Bexar County",
    countyCode: "48029",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.bcadonline.org/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Bexar Central Appraisal District",
    assessorPhone: "(210) 224-8511",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.bcadonline.org/",
    formTemplateName: "Bexar County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-15",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Bexar Central Appraisal Review Board",
    mailingAddressLine1: "411 N Frio St",
    mailingAddressCity: "San Antonio",
    mailingAddressState: "TX",
    mailingAddressZip: "78207",
  },
  {
    state: "TX",
    countyName: "Williamson County",
    countyCode: "48491",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://onlineappeals.wcad.org/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Williamson Central Appraisal District",
    assessorPhone: "(512) 930-3787",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://onlineappeals.wcad.org/",
    formTemplateName: "Williamson County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Williamson County Appraisal Review Board",
    mailingAddressLine1: "625 FM 1460",
    mailingAddressCity: "Georgetown",
    mailingAddressState: "TX",
    mailingAddressZip: "78626",
  },
  {
    state: "TX",
    countyName: "Denton County",
    countyCode: "48121",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dentoncad.com/public-portal/sign-in",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Denton Central Appraisal District",
    assessorPhone: "(940) 349-3800",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dentoncad.com/",
    formTemplateName: "Denton County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Denton Central Appraisal District",
    mailingAddressLine1: "3911 Morse Street",
    mailingAddressCity: "Denton",
    mailingAddressState: "TX",
    mailingAddressZip: "76208",
  },

  // ── FLORIDA EXPANSION ──────────────────────────────────────────────────────
  {
    state: "FL",
    countyName: "Broward County",
    countyCode: "12011",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://bcvab.broward.org/AxiaWeb2025/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Broward County Value Adjustment Board",
    assessorPhone: "(954) 357-7205",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://bcvab.broward.org/AxiaWeb2025/",
    formTemplateName: "Broward County VAB Petition (DR-486)",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 0,
    filingWindowStart: "08-18",
    filingWindowEnd: "09-17",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Broward County Value Adjustment Board",
    mailingAddressLine1: "115 South Andrews Avenue, Room 120",
    mailingAddressCity: "Fort Lauderdale",
    mailingAddressState: "FL",
    mailingAddressZip: "33301",
    intakeEmail: "vab@broward.org",
  },
  {
    state: "FL",
    countyName: "Palm Beach County",
    countyCode: "12099",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.mypalmbeachclerk.com/myvab",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Palm Beach County Value Adjustment Board",
    assessorPhone: "(561) 355-2431",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.mypalmbeachclerk.com/myvab",
    formTemplateName: "Palm Beach County VAB Petition (DR-486)",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 0,
    filingWindowStart: "08-01",
    filingWindowEnd: "09-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Palm Beach County Value Adjustment Board",
    mailingAddressLine1: "301 N. Olive Avenue, Rm. 206",
    mailingAddressCity: "West Palm Beach",
    mailingAddressState: "FL",
    mailingAddressZip: "33401",
    intakeEmail: "vab@mypalmbeachclerk.com",
  },
  {
    state: "FL",
    countyName: "Hillsborough County",
    countyCode: "12057",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://hcvab.hillsclerk.com/axiaweb2025/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Hillsborough County Value Adjustment Board",
    assessorPhone: "(813) 276-8100",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://hcvab.hillsclerk.com/axiaweb2025/",
    formTemplateName: "Hillsborough County VAB Petition (DR-486)",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 0,
    filingWindowStart: "08-01",
    filingWindowEnd: "09-12",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Clerk of the VAB",
    mailingAddressLine1: "601 East Kennedy Blvd., County Center 12th Floor",
    mailingAddressCity: "Tampa",
    mailingAddressState: "FL",
    mailingAddressZip: "33602",
    intakeEmail: "vab@hillsclerk.com",
  },
  {
    state: "FL",
    countyName: "Orange County",
    countyCode: "12095",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://vab.occompt.com/2025/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Orange County Value Adjustment Board",
    assessorPhone: "(407) 836-5115",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://vab.occompt.com/2025/",
    formTemplateName: "Orange County VAB Petition (DR-486)",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Orange County Value Adjustment Board",
    mailingAddressLine1: "P.O. Box 38",
    mailingAddressCity: "Orlando",
    mailingAddressState: "FL",
    mailingAddressZip: "32802",
    intakeEmail: "vab@occompt.com",
  },
  {
    state: "FL",
    countyName: "Pinellas County",
    countyCode: "12103",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://vabpetitions.mypinellasclerk.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Pinellas County Value Adjustment Board",
    assessorPhone: "(727) 464-3341",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://vabpetitions.mypinellasclerk.gov/",
    formTemplateName: "Pinellas County VAB Petition (DR-486)",
    poaEligible: 1,
    onlinePortalOnly: 1,
    pinOnlyLogin: 0,
    filingWindowStart: "07-01",
    filingWindowEnd: "09-12",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Pinellas County Value Adjustment Board",
    mailingAddressLine1: "315 Court Street, Fifth Floor",
    mailingAddressCity: "Clearwater",
    mailingAddressState: "FL",
    mailingAddressZip: "33756",
    intakeEmail: "Clerk.VAB@mypinellasclerk.gov",
  },

  // ── ARIZONA EXPANSION ──────────────────────────────────────────────────────
  {
    state: "AZ",
    countyName: "Maricopa County",
    countyCode: "04013",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://services.mcassessor.maricopa.gov/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Maricopa County Assessor",
    assessorPhone: "(602) 506-3406",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://services.mcassessor.maricopa.gov/",
    formTemplateName: "Maricopa County Notice of Claim",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-20",
    filingWindowEnd: "04-21",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Maricopa County Assessor's Office",
    mailingAddressLine1: "301 W Jefferson St",
    mailingAddressCity: "Phoenix",
    mailingAddressState: "AZ",
    mailingAddressZip: "85003",
  },

  // ── WASHINGTON EXPANSION ───────────────────────────────────────────────────
  {
    state: "WA",
    countyName: "King County",
    countyCode: "53033",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://blue.kingcounty.gov/Assessor/eAppeals/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "King County Assessor",
    assessorPhone: "(206) 296-7300",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://blue.kingcounty.gov/Assessor/eAppeals/",
    formTemplateName: "King County Board of Equalization Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-01",
    filingWindowEnd: "07-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "King County Board of Equalization",
    mailingAddressLine1: "516 Third Avenue, Room 1222",
    mailingAddressCity: "Seattle",
    mailingAddressState: "WA",
    mailingAddressZip: "98104",
  },

  // ── OHIO EXPANSION ─────────────────────────────────────────────────────────
  {
    state: "OH",
    countyName: "Franklin County",
    countyCode: "39049",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://efile.franklincountyoh.tyberacloud.net/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Franklin County Board of Revision",
    assessorPhone: "(614) 525-3230",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://efile.franklincountyoh.tyberacloud.net/",
    formTemplateName: "Franklin County BOR Complaint",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "11-12",
    filingWindowEnd: "03-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Franklin County Board of Revision",
    mailingAddressLine1: "373 S. High St., 20th Floor",
    mailingAddressCity: "Columbus",
    mailingAddressState: "OH",
    mailingAddressZip: "43215",
    intakeEmail: "BOR@franklincountyohio.gov",
  },
  {
    state: "OH",
    countyName: "Summit County",
    countyCode: "39153",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://summitohsmartfile.tylerhost.net/summitoh_sf/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Summit County Board of Revision",
    assessorPhone: "(330) 643-2636",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://summitohsmartfile.tylerhost.net/summitoh_sf/",
    formTemplateName: "Summit County BOR Complaint",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "03-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Summit County Board of Revision",
    mailingAddressLine1: "1180 S. Main St., Suite 250",
    mailingAddressCity: "Akron",
    mailingAddressState: "OH",
    mailingAddressZip: "44301",
    intakeEmail: "BOR@summitoh.net",
  },

  // ─── GEORGIA ─────────────────────────────────────────────────────────────
  {
    state: "GA",
    countyName: "Fulton County",
    countyCode: "13121",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.fultonassessor.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Fulton County Board of Assessors",
    assessorPhone: "(404) 612-6440",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.fultonassessor.org/appeal-forms/",
    formTemplateName: "Fulton County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Fulton County Board of Assessors",
    mailingAddressLine1: "235 Peachtree St NE, Suite 1400",
    mailingAddressCity: "Atlanta",
    mailingAddressState: "GA",
    mailingAddressZip: "30303",
    intakeEmail: "assessors@fultoncountyga.gov",
  },
  {
    state: "GA",
    countyName: "Gwinnett County",
    countyCode: "13135",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.gwinnettassessor.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Gwinnett County Board of Assessors",
    assessorPhone: "(770) 822-7200",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.gwinnettassessor.com/appeal",
    formTemplateName: "Gwinnett County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Gwinnett County Board of Assessors",
    mailingAddressLine1: "75 Langley Dr",
    mailingAddressCity: "Lawrenceville",
    mailingAddressState: "GA",
    mailingAddressZip: "30046",
    intakeEmail: "assessors@gwinnettcounty.com",
  },
  {
    state: "GA",
    countyName: "Cobb County",
    countyCode: "13067",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cobbassessor.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cobb County Board of Tax Assessors",
    assessorPhone: "(770) 528-3100",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cobbassessor.org/appeal",
    formTemplateName: "Cobb County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Cobb County Board of Tax Assessors",
    mailingAddressLine1: "736 Whitlock Ave NW, Suite 200",
    mailingAddressCity: "Marietta",
    mailingAddressState: "GA",
    mailingAddressZip: "30064",
    intakeEmail: "assessors@cobbcounty.org",
  },
  {
    state: "GA",
    countyName: "DeKalb County",
    countyCode: "13089",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dekalbcountyga.gov/assessors-office",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "DeKalb County Board of Tax Assessors",
    assessorPhone: "(404) 371-0841",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dekalbcountyga.gov/assessors-office/appeal",
    formTemplateName: "DeKalb County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "DeKalb County Board of Tax Assessors",
    mailingAddressLine1: "1300 Commerce Dr",
    mailingAddressCity: "Decatur",
    mailingAddressState: "GA",
    mailingAddressZip: "30030",
    intakeEmail: "assessors@dekalbcountyga.gov",
  },

  // ─── COLORADO ────────────────────────────────────────────────────────────
  {
    state: "CO",
    countyName: "Denver County",
    countyCode: "08031",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Assessors-Office",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Denver County Assessor",
    assessorPhone: "(720) 913-4162",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Assessors-Office/Appeal-Your-Assessment",
    formTemplateName: "Denver County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-08",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Denver County Assessor",
    mailingAddressLine1: "201 W Colfax Ave, Dept 406",
    mailingAddressCity: "Denver",
    mailingAddressState: "CO",
    mailingAddressZip: "80202",
    intakeEmail: "assessor@denvergov.org",
  },
  {
    state: "CO",
    countyName: "Arapahoe County",
    countyCode: "08005",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.arapahoegov.com/assessor",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Arapahoe County Assessor",
    assessorPhone: "(303) 795-4600",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.arapahoegov.com/assessor/appeal",
    formTemplateName: "Arapahoe County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-08",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Arapahoe County Assessor",
    mailingAddressLine1: "5334 S Prince St",
    mailingAddressCity: "Littleton",
    mailingAddressState: "CO",
    mailingAddressZip: "80120",
    intakeEmail: "assessor@arapahoegov.com",
  },
  {
    state: "CO",
    countyName: "Jefferson County",
    countyCode: "08059",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.jeffco.us/1448/Assessor",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Jefferson County Assessor",
    assessorPhone: "(303) 271-8600",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.jeffco.us/1448/Assessor",
    formTemplateName: "Jefferson County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-08",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Jefferson County Assessor",
    mailingAddressLine1: "100 Jefferson County Pkwy, Suite 2500",
    mailingAddressCity: "Golden",
    mailingAddressState: "CO",
    mailingAddressZip: "80419",
    intakeEmail: "assessor@jeffco.us",
  },
  {
    state: "CO",
    countyName: "El Paso County",
    countyCode: "08041",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.assessor.elpasoco.com/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "El Paso County Assessor",
    assessorPhone: "(719) 520-6600",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.assessor.elpasoco.com/appeal",
    formTemplateName: "El Paso County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-08",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "El Paso County Assessor",
    mailingAddressLine1: "1675 W Garden of the Gods Rd, Suite 2300",
    mailingAddressCity: "Colorado Springs",
    mailingAddressState: "CO",
    mailingAddressZip: "80907",
    intakeEmail: "assessor@elpasoco.com",
  },

  // ─── MINNESOTA ───────────────────────────────────────────────────────────
  {
    state: "MN",
    countyName: "Hennepin County",
    countyCode: "27053",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.hennepin.us/residents/property/property-tax-appeals",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Hennepin County Assessor",
    assessorPhone: "(612) 348-3046",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.hennepin.us/residents/property/property-tax-appeals",
    formTemplateName: "Hennepin County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "04-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Hennepin County Assessor",
    mailingAddressLine1: "300 S 6th St",
    mailingAddressCity: "Minneapolis",
    mailingAddressState: "MN",
    mailingAddressZip: "55487",
    intakeEmail: "assessor@hennepin.us",
  },
  {
    state: "MN",
    countyName: "Ramsey County",
    countyCode: "27123",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.ramseycounty.us/residents/property/property-tax-appeals",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Ramsey County Assessor",
    assessorPhone: "(651) 266-2131",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.ramseycounty.us/residents/property/property-tax-appeals",
    formTemplateName: "Ramsey County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "04-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Ramsey County Assessor",
    mailingAddressLine1: "90 W Plato Blvd, Suite 400",
    mailingAddressCity: "Saint Paul",
    mailingAddressState: "MN",
    mailingAddressZip: "55107",
    intakeEmail: "assessor@ramseycounty.us",
  },
  {
    state: "MN",
    countyName: "Dakota County",
    countyCode: "27037",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.dakota.mn.us/HomeProperty/PropertyValueTaxes/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Dakota County Assessor",
    assessorPhone: "(651) 438-4200",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.dakota.mn.us/HomeProperty/PropertyValueTaxes/Pages/default.aspx",
    formTemplateName: "Dakota County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "04-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Dakota County Assessor",
    mailingAddressLine1: "1590 Highway 55",
    mailingAddressCity: "Hastings",
    mailingAddressState: "MN",
    mailingAddressZip: "55033",
    intakeEmail: "assessor@co.dakota.mn.us",
  },

  // ─── MICHIGAN ────────────────────────────────────────────────────────────
  {
    state: "MI",
    countyName: "Wayne County",
    countyCode: "26163",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.waynecounty.com/elected/assessor/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Wayne County Assessor",
    assessorPhone: "(313) 224-5990",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.waynecounty.com/elected/assessor/",
    formTemplateName: "Wayne County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-01",
    filingWindowEnd: "03-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Wayne County Board of Review",
    mailingAddressLine1: "400 Monroe St, Suite 520",
    mailingAddressCity: "Detroit",
    mailingAddressState: "MI",
    mailingAddressZip: "48226",
    intakeEmail: "assessor@waynecounty.com",
  },
  {
    state: "MI",
    countyName: "Oakland County",
    countyCode: "26125",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.oakgov.com/assessments/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Oakland County Equalization Division",
    assessorPhone: "(248) 858-0740",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.oakgov.com/assessments/",
    formTemplateName: "Oakland County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-01",
    filingWindowEnd: "03-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Oakland County Equalization Division",
    mailingAddressLine1: "1200 N Telegraph Rd, Dept 479",
    mailingAddressCity: "Pontiac",
    mailingAddressState: "MI",
    mailingAddressZip: "48341",
    intakeEmail: "equalization@oakgov.com",
  },
  {
    state: "MI",
    countyName: "Macomb County",
    countyCode: "26099",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.macombgov.org/equalization",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Macomb County Equalization Department",
    assessorPhone: "(586) 469-5260",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.macombgov.org/equalization",
    formTemplateName: "Macomb County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-01",
    filingWindowEnd: "03-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Macomb County Board of Review",
    mailingAddressLine1: "120 N Main St",
    mailingAddressCity: "Mount Clemens",
    mailingAddressState: "MI",
    mailingAddressZip: "48043",
    intakeEmail: "equalization@macombgov.org",
  },

  // ─── NORTH CAROLINA ──────────────────────────────────────────────────────
  {
    state: "NC",
    countyName: "Mecklenburg County",
    countyCode: "37119",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.mecknc.gov/AssessorS-Office/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Mecklenburg County Assessor",
    assessorPhone: "(704) 336-4600",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.mecknc.gov/AssessorS-Office/Pages/Appeals.aspx",
    formTemplateName: "Mecklenburg County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Mecklenburg County Assessor",
    mailingAddressLine1: "700 E Stonewall St",
    mailingAddressCity: "Charlotte",
    mailingAddressState: "NC",
    mailingAddressZip: "28202",
    intakeEmail: "assessor@mecknc.gov",
  },
  {
    state: "NC",
    countyName: "Wake County",
    countyCode: "37183",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.wake.gov/departments-agencies/revenue-department/real-estate-appraisal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Wake County Revenue Department",
    assessorPhone: "(919) 856-5400",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.wake.gov/departments-agencies/revenue-department/real-estate-appraisal/appeal-your-value",
    formTemplateName: "Wake County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Wake County Revenue Department",
    mailingAddressLine1: "301 S McDowell St, Suite 3800",
    mailingAddressCity: "Raleigh",
    mailingAddressState: "NC",
    mailingAddressZip: "27601",
    intakeEmail: "revenue@wake.gov",
  },
  {
    state: "NC",
    countyName: "Guilford County",
    countyCode: "37081",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.guilfordcountync.gov/our-county/tax",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Guilford County Tax Department",
    assessorPhone: "(336) 641-3363",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.guilfordcountync.gov/our-county/tax/appeal",
    formTemplateName: "Guilford County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Guilford County Tax Department",
    mailingAddressLine1: "400 W Market St",
    mailingAddressCity: "Greensboro",
    mailingAddressState: "NC",
    mailingAddressZip: "27401",
    intakeEmail: "tax@guilfordcountync.gov",
  },

  // ─── VIRGINIA ────────────────────────────────────────────────────────────
  {
    state: "VA",
    countyName: "Fairfax County",
    countyCode: "51059",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.fairfaxcounty.gov/assessments/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Fairfax County Department of Tax Administration",
    assessorPhone: "(703) 222-8234",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.fairfaxcounty.gov/assessments/appeal",
    formTemplateName: "Fairfax County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Fairfax County Department of Tax Administration",
    mailingAddressLine1: "12000 Government Center Pkwy, Suite 357",
    mailingAddressCity: "Fairfax",
    mailingAddressState: "VA",
    mailingAddressZip: "22035",
    intakeEmail: "dtareo@fairfaxcounty.gov",
  },
  {
    state: "VA",
    countyName: "Prince William County",
    countyCode: "51153",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.pwcgov.org/government/dept/finance/Pages/Real-Estate-Assessments.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Prince William County Finance Department",
    assessorPhone: "(703) 792-6710",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.pwcgov.org/government/dept/finance/Pages/Real-Estate-Assessments.aspx",
    formTemplateName: "Prince William County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Prince William County Board of Equalization",
    mailingAddressLine1: "1 County Complex Court",
    mailingAddressCity: "Prince William",
    mailingAddressState: "VA",
    mailingAddressZip: "22192",
    intakeEmail: "finance@pwcgov.org",
  },

  // ─── MARYLAND ────────────────────────────────────────────────────────────
  {
    state: "MD",
    countyName: "Montgomery County",
    countyCode: "24031",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Maryland State Department of Assessments and Taxation",
    assessorPhone: "(410) 767-1184",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    formTemplateName: "Maryland SDAT Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "SDAT Assessment Office",
    mailingAddressLine1: "301 W Preston St, Room 801",
    mailingAddressCity: "Baltimore",
    mailingAddressState: "MD",
    mailingAddressZip: "21201",
    intakeEmail: "sdat.assessment@maryland.gov",
  },
  {
    state: "MD",
    countyName: "Prince George's County",
    countyCode: "24033",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Maryland SDAT — Prince George's County",
    assessorPhone: "(301) 952-2500",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    formTemplateName: "Maryland SDAT Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "SDAT — Prince George's County",
    mailingAddressLine1: "14735 Main St, Suite 356B",
    mailingAddressCity: "Upper Marlboro",
    mailingAddressState: "MD",
    mailingAddressZip: "20772",
    intakeEmail: "sdat.assessment@maryland.gov",
  },
  {
    state: "MD",
    countyName: "Baltimore County",
    countyCode: "24005",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Maryland SDAT — Baltimore County",
    assessorPhone: "(410) 512-4900",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    formTemplateName: "Maryland SDAT Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "SDAT — Baltimore County",
    mailingAddressLine1: "6 Saint Paul St, Suite 900",
    mailingAddressCity: "Baltimore",
    mailingAddressState: "MD",
    mailingAddressZip: "21202",
    intakeEmail: "sdat.assessment@maryland.gov",
  },

  // ─── WASHINGTON (additional) ─────────────────────────────────────────────────
  {
    state: "WA",
    countyName: "Pierce County",
    countyCode: "53053",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.piercecountywa.gov/1793/Assessor-Treasurer",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Pierce County Assessor-Treasurer",
    assessorPhone: "(253) 798-6111",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.piercecountywa.gov/1793/Assessor-Treasurer",
    formTemplateName: "Pierce County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "07-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Pierce County Board of Equalization",
    mailingAddressLine1: "2401 S 35th St, Room 142",
    mailingAddressCity: "Tacoma",
    mailingAddressState: "WA",
    mailingAddressZip: "98409",
    intakeEmail: "boe@piercecountywa.gov",
  },
  {
    state: "WA",
    countyName: "Snohomish County",
    countyCode: "53061",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://snohomishcountywa.gov/1254/Assessor",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Snohomish County Assessor",
    assessorPhone: "(425) 388-3433",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://snohomishcountywa.gov/1254/Assessor",
    formTemplateName: "Snohomish County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "07-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Snohomish County Board of Equalization",
    mailingAddressLine1: "3000 Rockefeller Ave, M/S 510",
    mailingAddressCity: "Everett",
    mailingAddressState: "WA",
    mailingAddressZip: "98201",
    intakeEmail: "boe@snohomishcountywa.gov",
  },

  // ─── CALIFORNIA (additional) ─────────────────────────────────────────────
  {
    state: "CA",
    countyName: "San Diego County",
    countyCode: "06073",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sandiegocounty.gov/content/sdc/assessor.html",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "San Diego County Assessor/Recorder/County Clerk",
    assessorPhone: "(619) 236-3771",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sandiegocounty.gov/content/sdc/assessor/assessment_appeals.html",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "San Diego County Assessment Appeals Board",
    mailingAddressLine1: "1600 Pacific Hwy, Room 402",
    mailingAddressCity: "San Diego",
    mailingAddressState: "CA",
    mailingAddressZip: "92101",
  },
  {
    state: "CA",
    countyName: "Orange County",
    countyCode: "06059",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.ocassessor.gov/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Orange County Assessor",
    assessorPhone: "(714) 834-2727",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.ocassessor.gov/assessment-appeals",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Orange County Assessment Appeals Board",
    mailingAddressLine1: "12 Civic Center Plaza, Room 107",
    mailingAddressCity: "Santa Ana",
    mailingAddressState: "CA",
    mailingAddressZip: "92701",
  },
  {
    state: "CA",
    countyName: "Riverside County",
    countyCode: "06065",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://assessor.countyofriverside.us/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Riverside County Assessor-County Clerk-Recorder",
    assessorPhone: "(951) 955-6200",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://assessor.countyofriverside.us/assessment-appeals",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Riverside County Assessment Appeals Board",
    mailingAddressLine1: "4080 Lemon St, 14th Floor",
    mailingAddressCity: "Riverside",
    mailingAddressState: "CA",
    mailingAddressZip: "92501",
  },
  {
    state: "CA",
    countyName: "San Bernardino County",
    countyCode: "06071",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sbcounty.gov/assessor/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "San Bernardino County Assessor-Recorder-County Clerk",
    assessorPhone: "(909) 387-8307",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sbcounty.gov/assessor/assessment-appeals",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "San Bernardino County Assessment Appeals Board",
    mailingAddressLine1: "385 N Arrowhead Ave, 2nd Floor",
    mailingAddressCity: "San Bernardino",
    mailingAddressState: "CA",
    mailingAddressZip: "92415",
  },
  {
    state: "CA",
    countyName: "Santa Clara County",
    countyCode: "06085",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sccassessor.org/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Santa Clara County Assessor",
    assessorPhone: "(408) 299-5300",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sccassessor.org/index.php/assessment-appeals",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Santa Clara County Assessment Appeals Board",
    mailingAddressLine1: "70 W Hedding St, 10th Floor",
    mailingAddressCity: "San Jose",
    mailingAddressState: "CA",
    mailingAddressZip: "95110",
  },
  {
    state: "CA",
    countyName: "Alameda County",
    countyCode: "06001",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.acgov.org/assessor/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Alameda County Assessor",
    assessorPhone: "(510) 272-3787",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.acgov.org/assessor/assessment-appeals.htm",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Alameda County Assessment Appeals Board",
    mailingAddressLine1: "1221 Oak St, Room 536",
    mailingAddressCity: "Oakland",
    mailingAddressState: "CA",
    mailingAddressZip: "94612",
  },
  {
    state: "CA",
    countyName: "Contra Costa County",
    countyCode: "06013",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.contracosta.ca.gov/1257/Assessors-Office",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Contra Costa County Assessor",
    assessorPhone: "(925) 313-7400",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.contracosta.ca.gov/1257/Assessors-Office",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Contra Costa County Assessment Appeals Board",
    mailingAddressLine1: "1025 Escobar St",
    mailingAddressCity: "Martinez",
    mailingAddressState: "CA",
    mailingAddressZip: "94553",
  },
  {
    state: "CA",
    countyName: "Sacramento County",
    countyCode: "06067",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.assessor.saccounty.gov/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Sacramento County Assessor",
    assessorPhone: "(916) 875-0700",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.assessor.saccounty.gov/assessment-appeals",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Sacramento County Assessment Appeals Board",
    mailingAddressLine1: "700 H St, Room 2450",
    mailingAddressCity: "Sacramento",
    mailingAddressState: "CA",
    mailingAddressZip: "95814",
  },
  {
    state: "CA",
    countyName: "Fresno County",
    countyCode: "06019",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.fresno.ca.us/departments/assessor-recorder",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Fresno County Assessor-Recorder",
    assessorPhone: "(559) 600-3534",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.fresno.ca.us/departments/assessor-recorder/assessment-appeals",
    formTemplateName: "Assessment Appeal Application (AAB-1)",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Fresno County Assessment Appeals Board",
    mailingAddressLine1: "2281 Tulare St, Room 304",
    mailingAddressCity: "Fresno",
    mailingAddressState: "CA",
    mailingAddressZip: "93721",
  },

  // ─── NEW YORK (additional) ────────────────────────────────────────────────
  {
    state: "NY",
    countyName: "Nassau County",
    countyCode: "36059",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.nassaucountyny.gov/1024/Assessment-Review-Commission",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Nassau County Assessment Review Commission",
    assessorPhone: "(516) 571-3214",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.nassaucountyny.gov/1024/Assessment-Review-Commission",
    formTemplateName: "Nassau County ARC Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "03-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Nassau County Assessment Review Commission",
    mailingAddressLine1: "240 Old Country Rd",
    mailingAddressCity: "Mineola",
    mailingAddressState: "NY",
    mailingAddressZip: "11501",
  },
  {
    state: "NY",
    countyName: "Suffolk County",
    countyCode: "36103",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.suffolkcountyny.gov/Departments/Real-Property-Tax-Service-Agency",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Suffolk County Real Property Tax Service Agency",
    assessorPhone: "(631) 852-1550",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.suffolkcountyny.gov/Departments/Real-Property-Tax-Service-Agency",
    formTemplateName: "Suffolk County Assessment Review Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "03-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Suffolk County Real Property Tax Service Agency",
    mailingAddressLine1: "300 Center Dr",
    mailingAddressCity: "Riverhead",
    mailingAddressState: "NY",
    mailingAddressZip: "11901",
  },
  {
    state: "NY",
    countyName: "Westchester County",
    countyCode: "36119",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://tax1.co.westchester.ny.us/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Westchester County Department of Finance",
    assessorPhone: "(914) 995-4325",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://tax1.co.westchester.ny.us/",
    formTemplateName: "Westchester County Assessment Review Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "03-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Westchester County Board of Assessment Review",
    mailingAddressLine1: "148 Martine Ave",
    mailingAddressCity: "White Plains",
    mailingAddressState: "NY",
    mailingAddressZip: "10601",
  },
  {
    state: "NY",
    countyName: "Monroe County",
    countyCode: "36055",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.monroecounty.gov/finance-index.php",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Monroe County Finance Department",
    assessorPhone: "(585) 753-1200",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.monroecounty.gov/finance-index.php",
    formTemplateName: "Monroe County Assessment Review Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "03-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Monroe County Board of Assessment Review",
    mailingAddressLine1: "39 W Main St, Room 102",
    mailingAddressCity: "Rochester",
    mailingAddressState: "NY",
    mailingAddressZip: "14614",
  },

  // ─── PENNSYLVANIA (additional) ────────────────────────────────────────────
  {
    state: "PA",
    countyName: "Allegheny County",
    countyCode: "42003",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.alleghenycounty.us/real-estate/appeals.aspx",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Allegheny County Office of Property Assessments",
    assessorPhone: "(412) 350-4600",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.alleghenycounty.us/real-estate/appeals.aspx",
    formTemplateName: "Allegheny County Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "03-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Allegheny County Board of Property Assessment Appeals",
    mailingAddressLine1: "542 Forbes Ave, Room 347",
    mailingAddressCity: "Pittsburgh",
    mailingAddressState: "PA",
    mailingAddressZip: "15219",
    intakeEmail: "opa@alleghenycounty.us",
  },
  {
    state: "PA",
    countyName: "Montgomery County",
    countyCode: "42091",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.montcopa.org/assessments",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Montgomery County Board of Assessment Appeals",
    assessorPhone: "(610) 278-3761",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.montcopa.org/assessments",
    formTemplateName: "Montgomery County PA Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "08-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Montgomery County Board of Assessment Appeals",
    mailingAddressLine1: "One Montgomery Plaza, Suite 301",
    mailingAddressCity: "Norristown",
    mailingAddressState: "PA",
    mailingAddressZip: "19401",
    intakeEmail: "assessments@montcopa.org",
  },

  // ─── TEXAS (additional) ───────────────────────────────────────────────────
  {
    state: "TX",
    countyName: "Fort Bend County",
    countyCode: "48157",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.fbcad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Fort Bend Central Appraisal District",
    assessorPhone: "(281) 344-8623",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.fbcad.org/forms/",
    formTemplateName: "Fort Bend County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Fort Bend Central Appraisal District",
    mailingAddressLine1: "2801 B F Terry Blvd",
    mailingAddressCity: "Rosenberg",
    mailingAddressState: "TX",
    mailingAddressZip: "77471",
  },
  {
    state: "TX",
    countyName: "Montgomery County",
    countyCode: "48339",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://mcad-tx.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Montgomery Central Appraisal District",
    assessorPhone: "(936) 756-3354",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://mcad-tx.org/forms/",
    formTemplateName: "Montgomery County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Montgomery Central Appraisal District",
    mailingAddressLine1: "109 Gladstell St",
    mailingAddressCity: "Conroe",
    mailingAddressState: "TX",
    mailingAddressZip: "77301",
  },
  {
    state: "TX",
    countyName: "Collin County",
    countyCode: "48085",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.collincad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Collin Central Appraisal District",
    assessorPhone: "(469) 742-9200",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.collincad.org/forms/",
    formTemplateName: "Collin County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Collin Central Appraisal District",
    mailingAddressLine1: "250 Eldorado Pkwy",
    mailingAddressCity: "McKinney",
    mailingAddressState: "TX",
    mailingAddressZip: "75069",
  },
  {
    state: "TX",
    countyName: "Tarrant County",
    countyCode: "48439",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.tad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Tarrant Appraisal District",
    assessorPhone: "(817) 284-0024",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.tad.org/forms/",
    formTemplateName: "Tarrant County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Tarrant Appraisal District",
    mailingAddressLine1: "2500 Handley-Ederville Rd",
    mailingAddressCity: "Fort Worth",
    mailingAddressState: "TX",
    mailingAddressZip: "76118",
  },
  {
    state: "TX",
    countyName: "El Paso County",
    countyCode: "48141",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.epcad.org/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "El Paso Central Appraisal District",
    assessorPhone: "(915) 780-2000",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.epcad.org/forms/",
    formTemplateName: "El Paso County ARB Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "El Paso Central Appraisal District",
    mailingAddressLine1: "5801 Trowbridge Dr",
    mailingAddressCity: "El Paso",
    mailingAddressState: "TX",
    mailingAddressZip: "79925",
  },

  // ─── FLORIDA (additional) ─────────────────────────────────────────────────
  {
    state: "FL",
    countyName: "Duval County",
    countyCode: "12031",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.coj.net/departments/property-appraiser",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Duval County Property Appraiser",
    assessorPhone: "(904) 630-2020",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.coj.net/departments/property-appraiser/value-adjustment-board",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Duval County Value Adjustment Board",
    mailingAddressLine1: "117 W Duval St, Suite 400",
    mailingAddressCity: "Jacksonville",
    mailingAddressState: "FL",
    mailingAddressZip: "32202",
  },
  {
    state: "FL",
    countyName: "Lee County",
    countyCode: "12071",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.leepa.org/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Lee County Property Appraiser",
    assessorPhone: "(239) 533-6100",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.leepa.org/vab/",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Lee County Value Adjustment Board",
    mailingAddressLine1: "2115 Second St",
    mailingAddressCity: "Fort Myers",
    mailingAddressState: "FL",
    mailingAddressZip: "33901",
  },
  {
    state: "FL",
    countyName: "Sarasota County",
    countyCode: "12115",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sc-pa.com/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Sarasota County Property Appraiser",
    assessorPhone: "(941) 861-8200",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sc-pa.com/vab/",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Sarasota County Value Adjustment Board",
    mailingAddressLine1: "1660 Ringling Blvd",
    mailingAddressCity: "Sarasota",
    mailingAddressState: "FL",
    mailingAddressZip: "34236",
  },
  {
    state: "FL",
    countyName: "Polk County",
    countyCode: "12105",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.polkpa.org/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Polk County Property Appraiser",
    assessorPhone: "(863) 534-4777",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.polkpa.org/vab/",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Polk County Value Adjustment Board",
    mailingAddressLine1: "255 N Wilson Ave",
    mailingAddressCity: "Bartow",
    mailingAddressState: "FL",
    mailingAddressZip: "33830",
  },
  {
    state: "FL",
    countyName: "Volusia County",
    countyCode: "12127",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.vcpa.vcgov.org/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Volusia County Property Appraiser",
    assessorPhone: "(386) 736-5901",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.vcpa.vcgov.org/vab/",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Volusia County Value Adjustment Board",
    mailingAddressLine1: "123 W Indiana Ave",
    mailingAddressCity: "DeLand",
    mailingAddressState: "FL",
    mailingAddressZip: "32720",
  },
  {
    state: "FL",
    countyName: "Pasco County",
    countyCode: "12101",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.pascopa.com/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Pasco County Property Appraiser",
    assessorPhone: "(352) 521-4433",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.pascopa.com/vab/",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Pasco County Value Adjustment Board",
    mailingAddressLine1: "7530 Little Rd",
    mailingAddressCity: "New Port Richey",
    mailingAddressState: "FL",
    mailingAddressZip: "34654",
  },

  // ─── ILLINOIS (additional) ────────────────────────────────────────────────
  {
    state: "IL",
    countyName: "Lake County",
    countyCode: "17097",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.lakecountyil.gov/assessor",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Lake County Supervisor of Assessments",
    assessorPhone: "(847) 377-2050",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.lakecountyil.gov/assessor/appeal",
    formTemplateName: "Lake County Assessment Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "06-01",
    filingWindowEnd: "09-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Lake County Board of Review",
    mailingAddressLine1: "18 N County St, Suite 7-100",
    mailingAddressCity: "Waukegan",
    mailingAddressState: "IL",
    mailingAddressZip: "60085",
    intakeEmail: "assessor@lakecountyil.gov",
  },
  {
    state: "IL",
    countyName: "Will County",
    countyCode: "17197",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.willcountyillinois.com/County-Offices/Supervisor-of-Assessments",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Will County Supervisor of Assessments",
    assessorPhone: "(815) 740-4648",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.willcountyillinois.com/County-Offices/Supervisor-of-Assessments",
    formTemplateName: "Will County Assessment Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "06-01",
    filingWindowEnd: "09-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Will County Board of Review",
    mailingAddressLine1: "302 N Chicago St",
    mailingAddressCity: "Joliet",
    mailingAddressState: "IL",
    mailingAddressZip: "60432",
    intakeEmail: "assessments@willcountyillinois.com",
  },
  {
    state: "IL",
    countyName: "Kane County",
    countyCode: "17089",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.countyofkane.org/Assessments/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Kane County Supervisor of Assessments",
    assessorPhone: "(630) 232-3565",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.countyofkane.org/Assessments/Pages/default.aspx",
    formTemplateName: "Kane County Assessment Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "06-01",
    filingWindowEnd: "09-30",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Kane County Board of Review",
    mailingAddressLine1: "719 S Batavia Ave",
    mailingAddressCity: "Geneva",
    mailingAddressState: "IL",
    mailingAddressZip: "60134",
    intakeEmail: "assessments@countyofkane.org",
  },

  // ─── ARIZONA (additional) ─────────────────────────────────────────────────
  {
    state: "AZ",
    countyName: "Pima County",
    countyCode: "04019",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.assessor.pima.gov/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Pima County Assessor",
    assessorPhone: "(520) 724-8630",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.assessor.pima.gov/appeal",
    formTemplateName: "Pima County Assessment Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "11-01",
    filingWindowEnd: "01-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Pima County Assessor",
    mailingAddressLine1: "240 N Stone Ave",
    mailingAddressCity: "Tucson",
    mailingAddressState: "AZ",
    mailingAddressZip: "85701",
    intakeEmail: "assessor@pima.gov",
  },
  {
    state: "AZ",
    countyName: "Pinal County",
    countyCode: "04021",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.pinalcountyaz.gov/assessor/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Pinal County Assessor",
    assessorPhone: "(520) 866-6361",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.pinalcountyaz.gov/assessor/appeal",
    formTemplateName: "Pinal County Assessment Appeal Form",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "11-01",
    filingWindowEnd: "01-31",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Pinal County Assessor",
    mailingAddressLine1: "31 N Pinal St, Bldg E",
    mailingAddressCity: "Florence",
    mailingAddressState: "AZ",
    mailingAddressZip: "85132",
    intakeEmail: "assessor@pinalcountyaz.gov",
  },

  // ─── NEW JERSEY (additional) ──────────────────────────────────────────────
  {
    state: "NJ",
    countyName: "Middlesex County",
    countyCode: "34023",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.middlesexcountynj.gov/government/departments/tax-board",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Middlesex County Tax Board",
    assessorPhone: "(732) 745-3350",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.middlesexcountynj.gov/government/departments/tax-board",
    formTemplateName: "NJ Tax Court Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Middlesex County Board of Taxation",
    mailingAddressLine1: "75 Bayard St",
    mailingAddressCity: "New Brunswick",
    mailingAddressState: "NJ",
    mailingAddressZip: "08901",
    intakeEmail: "taxboard@co.middlesex.nj.us",
  },
  {
    state: "NJ",
    countyName: "Monmouth County",
    countyCode: "34025",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.monmouth.nj.us/departments.aspx?deptID=2",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Monmouth County Tax Board",
    assessorPhone: "(732) 431-7400",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.monmouth.nj.us/departments.aspx?deptID=2",
    formTemplateName: "NJ Tax Court Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Monmouth County Board of Taxation",
    mailingAddressLine1: "1 E Main St",
    mailingAddressCity: "Freehold",
    mailingAddressState: "NJ",
    mailingAddressZip: "07728",
    intakeEmail: "taxboard@co.monmouth.nj.us",
  },
  {
    state: "NJ",
    countyName: "Morris County",
    countyCode: "34027",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://morriscountynj.gov/departments/tax-board/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Morris County Tax Board",
    assessorPhone: "(973) 285-6707",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://morriscountynj.gov/departments/tax-board/",
    formTemplateName: "NJ Tax Court Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Morris County Board of Taxation",
    mailingAddressLine1: "PO Box 900",
    mailingAddressCity: "Morristown",
    mailingAddressState: "NJ",
    mailingAddressZip: "07963",
    intakeEmail: "taxboard@co.morris.nj.us",
  },
  {
    state: "NJ",
    countyName: "Union County",
    countyCode: "34039",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.ucnj.org/tax-board/",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Union County Tax Board",
    assessorPhone: "(908) 527-4775",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.ucnj.org/tax-board/",
    formTemplateName: "NJ Tax Court Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Union County Board of Taxation",
    mailingAddressLine1: "271 North Broad St",
    mailingAddressCity: "Elizabeth",
    mailingAddressState: "NJ",
    mailingAddressZip: "07207",
    intakeEmail: "taxboard@ucnj.org",
  },
  {
    state: "NJ",
    countyName: "Ocean County",
    countyCode: "34029",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.ocean.nj.us/taxboard",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Ocean County Tax Board",
    assessorPhone: "(732) 929-2008",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.ocean.nj.us/taxboard",
    formTemplateName: "NJ Tax Court Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "04-01",
    preferredChannel: "mail_certified",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Ocean County Board of Taxation",
    mailingAddressLine1: "101 Hooper Ave, Bldg A",
    mailingAddressCity: "Toms River",
    mailingAddressState: "NJ",
    mailingAddressZip: "08753",
    intakeEmail: "taxboard@co.ocean.nj.us",
  },
  ...COUNTY_SEED_EXPANSION,
  ...COUNTY_SEED_PHASE3,
];
export const adminRouter = router({
  /**
   * Seed counties database (admin only)
   */
  seedCounties: protectedProcedure.mutation(async ({ ctx }) => {
    if (ctx.user?.role !== "admin") {
      throw new TRPCError({
        code: "FORBIDDEN",
        message: "Admin access required",
      });
    }

    const db = await getDb();
    if (!db) throw new Error("Database unavailable");

    try {
      let seeded = 0;
      for (const county of COUNTY_SEED) {
        // onDuplicateKeyUpdate now backfills the channel-routing fields too,
        // so adding mailing addresses for previously-portal-only counties
        // takes effect on the next admin seed run without a manual SQL
        // migration. Every field explicitly listed below is one we want to
        // treat as authoritative in this seed.
        const update: Record<string, unknown> = {
          portalUrl: county.portalUrl,
          assessorPhone: county.assessorPhone,
          hearingScheduleDays: county.hearingScheduleDays,
        };
        const mailFields = [
          "filingWindowStart",
          "filingWindowEnd",
          "preferredChannel",
          "fallbackChannel",
          "mailingAddressName",
          "mailingAddressLine1",
          "mailingAddressLine2",
          "mailingAddressCity",
          "mailingAddressState",
          "mailingAddressZip",
          "intakeEmail",
          "poaEligible",
          "onlinePortalOnly",
          "pinOnlyLogin",
        ] as const;
        for (const f of mailFields) {
          const v = (county as Record<string, unknown>)[f];
          if (v !== undefined) update[f] = v;
        }
        await db.insert(counties).values(county as any).onDuplicateKeyUpdate({
          set: update,
        });
        seeded++;
      }

      return {
        success: true,
        message: `Seeded ${seeded} counties successfully`,
        count: seeded,
      };
    } catch (error) {
      console.error("[Admin] Error seeding counties:", error);
      throw new TRPCError({
        code: "INTERNAL_SERVER_ERROR",
        message: "Failed to seed counties",
      });
    }
  }),

  /**
   * Seed filing recipes database (admin only)
   * Upserts all draft recipes from RECIPE_SEEDS + RECIPE_SEEDS_EXPANSION.
   * Recipes are inserted with verificationStatus='draft' — they must be
   * manually promoted to 'staging' or 'verified' after human QA.
   */
  seedRecipes: protectedProcedure.mutation(async ({ ctx }) => {
    if (ctx.user?.role !== "admin") {
      throw new TRPCError({
        code: "FORBIDDEN",
        message: "Admin access required",
      });
    }

    const db = await getDb();
    if (!db) throw new Error("Database unavailable");

    const allRecipes = [...RECIPE_SEEDS, ...RECIPE_SEEDS_EXPANSION];
    let seeded = 0;
    let skipped = 0;
    const errors: string[] = [];

    for (const seed of allRecipes) {
      try {
        // Look up the county by countyCode to get the real DB id
        const county = await db
          .select({ id: counties.id })
          .from(counties)
          .where(eq(counties.countyCode, seed.countyCode))
          .limit(1)
          .then((r: any[]) => r[0]);

        if (!county) {
          skipped++;
          errors.push(`County not found: ${seed.countyCode} (${seed.countyName})`);
          continue;
        }

        // Check if a recipe already exists for this county (any version)
        const existing = await db
          .select({ id: filingRecipes.id })
          .from(filingRecipes)
          .where(eq(filingRecipes.countyId, county.id))
          .limit(1)
          .then((r: any[]) => r[0]);

        if (existing) {
          // Update the existing recipe's steps, portalUrl, and notes
          await db
            .update(filingRecipes)
            .set({
              steps: JSON.stringify(seed.recipe.steps),
              portalUrl: seed.portalUrl,
              notes: seed.notes ?? null,
              validFrom: seed.validFrom ? new Date(seed.validFrom) : null,
              validUntil: seed.validUntil ? new Date(seed.validUntil) : null,
            })
            .where(eq(filingRecipes.id, existing.id));
        } else {
          // Insert a new draft recipe
          await db.insert(filingRecipes).values({
            countyId: county.id,
            version: seed.recipe.version ?? 1,
            portalUrl: seed.portalUrl,
            steps: JSON.stringify(seed.recipe.steps),
            validFrom: seed.validFrom ? new Date(seed.validFrom) : null,
            validUntil: seed.validUntil ? new Date(seed.validUntil) : null,
            verificationStatus: "draft",
            notes: seed.notes ?? null,
            active: true,
          });
        }
        seeded++;
      } catch (err) {
        errors.push(`Failed ${seed.countyCode}: ${String(err)}`);
      }
    }

    return {
      success: true,
      message: `Seeded ${seeded} recipes (${skipped} skipped — county not found yet)`,
      count: seeded,
      skipped,
      errors: errors.slice(0, 20),
    };
  }),
});
