CREATE TABLE `counties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`state` varchar(2) NOT NULL,
	`countyName` varchar(100) NOT NULL,
	`countyCode` varchar(10),
	`poaDeadlineDays` int,
	`proSeDeadlineDays` int,
	`hasOnlinePortal` boolean DEFAULT false,
	`portalUrl` varchar(500),
	`acceptsEmail` boolean DEFAULT false,
	`acceptsMail` boolean DEFAULT false,
	`acceptsInPerson` boolean DEFAULT false,
	`assessorName` varchar(255),
	`assessorPhone` varchar(20),
	`assessorEmail` varchar(320),
	`arbName` varchar(255),
	`arbPhone` varchar(20),
	`arbEmail` varchar(320),
	`filingFee` int,
	`hearingFee` int,
	`hearingFormat` enum('in-person','virtual','hybrid','mail') DEFAULT 'in-person',
	`hearingScheduleDays` int,
	`requiresAttorney` boolean DEFAULT false,
	`formTemplateUrl` varchar(500),
	`formTemplateName` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `counties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `filing_tiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`tier` enum('pro-se','poa') NOT NULL,
	`proSePrice` int,
	`contingencyPercentage` int,
	`paymentStatus` enum('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',
	`paymentMethod` enum('stripe','none'),
	`stripePaymentIntentId` varchar(255),
	`contingencyPaidDate` timestamp,
	`contingencyAmount` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `filing_tiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paralegals_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`poaFilingId` int NOT NULL,
	`assignedTo` varchar(255),
	`priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
	`status` enum('queued','in-progress','completed','blocked') NOT NULL DEFAULT 'queued',
	`queuedAt` timestamp NOT NULL DEFAULT (now()),
	`startedAt` timestamp,
	`completedAt` timestamp,
	`deadline` timestamp,
	`notes` text,
	`blockers` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paralegals_queue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `poa_filings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`countyId` int NOT NULL,
	`status` enum('pending','filed','acknowledged','scheduled','hearing-held','decided','failed') NOT NULL DEFAULT 'pending',
	`filingDate` timestamp,
	`filedBy` varchar(255),
	`hearingDate` timestamp,
	`hearingTime` varchar(20),
	`hearingLocation` varchar(255),
	`hearingFormat` enum('in-person','virtual','mail'),
	`outcome` enum('won','lost','settled','withdrawn','pending') DEFAULT 'pending',
	`newAssessedValue` int,
	`assessmentReduction` int,
	`confirmationNumber` varchar(100),
	`portalUrl` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `poa_filings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pro_se_filings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`countyId` int NOT NULL,
	`status` enum('started','forms-generated','documents-sent','filed','hearing-scheduled','completed','abandoned') NOT NULL DEFAULT 'started',
	`formsPdfUrl` varchar(500),
	`checklistPdfUrl` varchar(500),
	`instructionsPdfUrl` varchar(500),
	`formsSentDate` timestamp,
	`userFiledDate` timestamp,
	`confirmationReceived` boolean DEFAULT false,
	`coachingEmailsSent` int DEFAULT 0,
	`lastCoachingEmail` timestamp,
	`hearingDate` timestamp,
	`outcome` enum('won','lost','pending','unknown') DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pro_se_filings_id` PRIMARY KEY(`id`)
);
