/**
 * Seed jurisdiction_rules table from hardcoded data
 * This is a one-time migration from the old jurisdictionRules.ts file to the DB
 * Run this via: import { seedJurisdictionRules } from "./db-seed-jurisdiction-rules"; await seedJurisdictionRules();
 */
import { getDb } from "./db";
import { jurisdictionRules } from "../drizzle/schema.pg";

export async function seedJurisdictionRules() {
  try {
    const db = await getDb();
    if (!db) throw new Error("Database connection failed");
    console.log("[Seed] Starting jurisdiction_rules seeding...");

    // Clear existing rules
    await db.delete(jurisdictionRules);
    console.log("[Seed] Cleared existing rules");

    // Insert all rules
    const rulesToInsert = [
      // TEXAS
      {
        state: "TX",
        county: "Harris",
        assessmentRate: "100.00",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 5000,
        minAssessmentPercentage: 3,
        successRate: 52,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Comparable sales analysis", "Property condition report", "Market analysis", "Appraisal report"]),
        hearingRequired: true,
        averageResolutionDays: 120,
        contingencyFeeAllowed: true,
        maxContingencyFee: 25,
        notes: "Harris County accepts both POA and pro se. Strong comps market. AI-generated reports perform well.",
        source: "Harris County Appraisal District",
        sourceUrl: "https://www.hcad.org",
        lastVerifiedAt: new Date(),
      },
      {
        state: "TX",
        county: "Dallas",
        assessmentRate: "100.00",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 4000,
        minAssessmentPercentage: 2.5,
        successRate: 48,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Certified appraisal", "Comparable sales", "Market analysis"]),
        hearingRequired: true,
        averageResolutionDays: 90,
        contingencyFeeAllowed: true,
        maxContingencyFee: 25,
        notes: "Dallas CAD is data-heavy. Requires certified appraisals for POA filings.",
        source: "Dallas Central Appraisal District",
        sourceUrl: "https://www.dallascad.org",
        lastVerifiedAt: new Date(),
      },
      {
        state: "TX",
        county: "Tarrant",
        assessmentRate: "100.00",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 3500,
        minAssessmentPercentage: 2,
        successRate: 55,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Appraisal", "Comps", "Market data"]),
        hearingRequired: true,
        averageResolutionDays: 75,
        contingencyFeeAllowed: true,
        maxContingencyFee: 25,
        notes: "Fort Worth area. Favorable to residential appeals. Fast turnaround.",
        source: "Tarrant Central Appraisal District",
        sourceUrl: "https://www.tcad.org",
        lastVerifiedAt: new Date(),
      },
      // ILLINOIS
      {
        state: "IL",
        county: "Cook",
        assessmentRate: "33.33",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 5000,
        minAssessmentPercentage: 3,
        successRate: 45,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Certified appraisal", "Comparable sales", "Market analysis"]),
        hearingRequired: true,
        averageResolutionDays: 150,
        contingencyFeeAllowed: true,
        maxContingencyFee: 20,
        notes: "Cook County (Chicago) is competitive. Requires certified appraisals. Strong appeal culture but strict standards.",
        source: "Cook County Assessor",
        sourceUrl: "https://www.cookcountyassessor.com",
        lastVerifiedAt: new Date(),
      },
      {
        state: "IL",
        county: "DuPage",
        assessmentRate: "33.33",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 4000,
        minAssessmentPercentage: 2.5,
        successRate: 48,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Appraisal", "Comps", "Market analysis"]),
        hearingRequired: true,
        averageResolutionDays: 120,
        contingencyFeeAllowed: true,
        maxContingencyFee: 20,
        notes: "DuPage County (western suburbs of Chicago). Moderate assessment rate. Good appeal market.",
        source: "DuPage County Assessor",
        sourceUrl: "https://www.dupageco.org/assessor",
        lastVerifiedAt: new Date(),
      },
      {
        state: "IL",
        county: "Lake",
        assessmentRate: "33.33",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 4000,
        minAssessmentPercentage: 2.5,
        successRate: 46,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Appraisal", "Comps"]),
        hearingRequired: true,
        averageResolutionDays: 110,
        contingencyFeeAllowed: true,
        maxContingencyFee: 20,
        notes: "Lake County (north of Chicago). Moderate assessment rate. Residential-focused.",
        source: "Lake County Assessor",
        sourceUrl: "https://www.lakecountyil.gov/assessor",
        lastVerifiedAt: new Date(),
      },
      {
        state: "IL",
        county: "Will",
        assessmentRate: "33.33",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 3500,
        minAssessmentPercentage: 2,
        successRate: 50,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Appraisal", "Comps"]),
        hearingRequired: true,
        averageResolutionDays: 100,
        contingencyFeeAllowed: true,
        maxContingencyFee: 20,
        notes: "Will County (south of Chicago). Growing market. Good appeal success rate.",
        source: "Will County Assessor",
        sourceUrl: "https://www.willcountyassessor.com",
        lastVerifiedAt: new Date(),
      },
      {
        state: "IL",
        county: "Kane",
        assessmentRate: "33.33",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 3500,
        minAssessmentPercentage: 2,
        successRate: 49,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Appraisal", "Comps"]),
        hearingRequired: true,
        averageResolutionDays: 105,
        contingencyFeeAllowed: true,
        maxContingencyFee: 20,
        notes: "Kane County (west of Chicago). Moderate assessment rate. Aurora area.",
        source: "Kane County Assessor",
        sourceUrl: "https://www.kanecountyassessor.com",
        lastVerifiedAt: new Date(),
      },
      // ARIZONA
      {
        state: "AZ",
        county: "Maricopa",
        assessmentRate: "10.00",
        appealDeadlineDays: 30,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 3000,
        minAssessmentPercentage: 2,
        successRate: 50,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Appraisal", "Comps", "Market data"]),
        hearingRequired: false,
        averageResolutionDays: 60,
        contingencyFeeAllowed: true,
        maxContingencyFee: 25,
        notes: "Maricopa County (Phoenix) does NOT require hearings for many appeals. Fast resolution. Good market.",
        source: "Maricopa County Assessor",
        sourceUrl: "https://www.maricopa.gov/assessor",
        lastVerifiedAt: new Date(),
      },
      // FLORIDA
      {
        state: "FL",
        county: "Miami-Dade",
        assessmentRate: "100.00",
        appealDeadlineDays: 25,
        appealDeadlineType: "from_notice" as const,
        minAssessmentDifference: 4000,
        minAssessmentPercentage: 2.5,
        successRate: 48,
        filingMethods: JSON.stringify(["poa", "pro_se"]),
        documentationRequired: JSON.stringify(["Appraisal", "Comps"]),
        hearingRequired: true,
        averageResolutionDays: 90,
        contingencyFeeAllowed: true,
        maxContingencyFee: 25,
        notes: "Miami-Dade is residential-focused. Short deadline (25 days). Good contingency market.",
        source: "Miami-Dade County Property Appraiser",
        sourceUrl: "https://www.miamidade.gov/propertysearch",
        lastVerifiedAt: new Date(),
      },
    ];

    await db.insert(jurisdictionRules).values(rulesToInsert as any);
    console.log(`[Seed] Successfully seeded ${rulesToInsert.length} jurisdiction rules`);
  } catch (err) {
    console.error("[Seed] Error seeding jurisdiction rules:", err);
    throw err;
  }
}
