/**
 * County Seed Expansion — Phase 2
 *
 * 60+ additional counties with verified online property tax appeal portals.
 * All counties here use preferredChannel: "portal" and have a known public
 * online filing URL. Filing recipes are in filingRecipes.seed.ts.
 *
 * Sources: county assessor websites, state VAB/ARB portals, IAAO directory.
 * Portal URLs verified as of April 2026.
 */

export type CountySeedEntry = {
  state: string;
  countyName: string;
  countyCode: string;
  poaDeadlineDays: number;
  proSeDeadlineDays: number;
  hasOnlinePortal: number;
  portalUrl: string;
  acceptsEmail: number;
  acceptsMail: number;
  acceptsInPerson: number;
  assessorName: string;
  assessorPhone: string;
  hearingFormat: string;
  hearingScheduleDays: number;
  requiresAttorney: number;
  formTemplateUrl: string;
  formTemplateName: string;
  poaEligible: number;
  onlinePortalOnly: number;
  pinOnlyLogin: number;
  filingWindowStart: string;
  filingWindowEnd: string;
  preferredChannel: string;
  fallbackChannel: string;
  mailingAddressName: string;
  mailingAddressLine1: string;
  mailingAddressCity: string;
  mailingAddressState: string;
  mailingAddressZip: string;
  intakeEmail?: string;
};

export const COUNTY_SEED_EXPANSION: CountySeedEntry[] = [

  // ─── TEXAS (additional portal counties) ──────────────────────────────────
  {
    state: "TX",
    countyName: "Galveston County",
    countyCode: "48167",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.galvestoncad.org/ifile/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Galveston Central Appraisal District",
    assessorPhone: "(409) 935-1980",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.galvestoncad.org/ifile/",
    formTemplateName: "GCAD iFile Protest",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Galveston Central Appraisal District",
    mailingAddressLine1: "9850 Emmett F. Lowry Expressway",
    mailingAddressCity: "Texas City",
    mailingAddressState: "TX",
    mailingAddressZip: "77591",
  },
  {
    state: "TX",
    countyName: "Brazoria County",
    countyCode: "48039",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.brazoriacad.org/protest-online.html",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Brazoria County Appraisal District",
    assessorPhone: "(979) 849-7792",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.brazoriacad.org/protest-online.html",
    formTemplateName: "BCAD Online Protest",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Brazoria County Appraisal District",
    mailingAddressLine1: "500 N Chenango St",
    mailingAddressCity: "Angleton",
    mailingAddressState: "TX",
    mailingAddressZip: "77515",
  },
  {
    state: "TX",
    countyName: "Nueces County",
    countyCode: "48355",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.nuecescad.net/ifile",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Nueces County Appraisal District",
    assessorPhone: "(361) 881-9978",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.nuecescad.net/ifile",
    formTemplateName: "NCAD iFile Protest",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Nueces County Appraisal District",
    mailingAddressLine1: "201 N Chaparral St",
    mailingAddressCity: "Corpus Christi",
    mailingAddressState: "TX",
    mailingAddressZip: "78401",
  },
  {
    state: "TX",
    countyName: "Lubbock County",
    countyCode: "48303",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.lubbockcad.org/ifile",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Lubbock Central Appraisal District",
    assessorPhone: "(806) 762-5000",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.lubbockcad.org/ifile",
    formTemplateName: "LCAD iFile Protest",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Lubbock Central Appraisal District",
    mailingAddressLine1: "1715 26th St",
    mailingAddressCity: "Lubbock",
    mailingAddressState: "TX",
    mailingAddressZip: "79411",
  },
  {
    state: "TX",
    countyName: "Jefferson County",
    countyCode: "48245",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.jcad.org/ifile",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Jefferson County Appraisal District",
    assessorPhone: "(409) 840-9944",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.jcad.org/ifile",
    formTemplateName: "JCAD iFile Protest",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Jefferson County Appraisal District",
    mailingAddressLine1: "4610 S 4th St",
    mailingAddressCity: "Beaumont",
    mailingAddressState: "TX",
    mailingAddressZip: "77705",
  },
  {
    state: "TX",
    countyName: "Smith County",
    countyCode: "48423",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.smithcad.org/ifile",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Smith County Appraisal District",
    assessorPhone: "(903) 510-8600",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.smithcad.org/ifile",
    formTemplateName: "SCAD iFile Protest",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Smith County Appraisal District",
    mailingAddressLine1: "245 SSE Loop 323",
    mailingAddressCity: "Tyler",
    mailingAddressState: "TX",
    mailingAddressZip: "75702",
  },
  {
    state: "TX",
    countyName: "McLennan County",
    countyCode: "48309",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.mclennancad.org/ifile",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "McLennan County Appraisal District",
    assessorPhone: "(254) 752-9864",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.mclennancad.org/ifile",
    formTemplateName: "MCAD iFile Protest",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 1,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "McLennan County Appraisal District",
    mailingAddressLine1: "315 S 26th St",
    mailingAddressCity: "Waco",
    mailingAddressState: "TX",
    mailingAddressZip: "76710",
  },

  // ─── FLORIDA (additional portal counties) ────────────────────────────────
  {
    state: "FL",
    countyName: "Sarasota County",
    countyCode: "12115",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sarasotaclerk.com/vab",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Sarasota County Value Adjustment Board",
    assessorPhone: "(941) 861-7400",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sarasotaclerk.com/vab",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Sarasota County Value Adjustment Board",
    mailingAddressLine1: "2000 Main St",
    mailingAddressCity: "Sarasota",
    mailingAddressState: "FL",
    mailingAddressZip: "34237",
    intakeEmail: "vab@sarasotaclerk.com",
  },
  {
    state: "FL",
    countyName: "Volusia County",
    countyCode: "12127",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.volusiavab.com/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Volusia County Value Adjustment Board",
    assessorPhone: "(386) 736-5901",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.volusiavab.com/",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Volusia County Value Adjustment Board",
    mailingAddressLine1: "123 W Indiana Ave",
    mailingAddressCity: "DeLand",
    mailingAddressState: "FL",
    mailingAddressZip: "32720",
    intakeEmail: "vab@volusia.org",
  },
  {
    state: "FL",
    countyName: "Pasco County",
    countyCode: "12101",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.pascoclerk.com/vab",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Pasco County Value Adjustment Board",
    assessorPhone: "(352) 521-4274",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.pascoclerk.com/vab",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Pasco County Value Adjustment Board",
    mailingAddressLine1: "38053 Live Oak Ave",
    mailingAddressCity: "Dade City",
    mailingAddressState: "FL",
    mailingAddressZip: "33523",
    intakeEmail: "vab@pascoclerk.com",
  },
  {
    state: "FL",
    countyName: "Seminole County",
    countyCode: "12117",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.seminoleclerk.org/vab",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Seminole County Value Adjustment Board",
    assessorPhone: "(407) 665-4330",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.seminoleclerk.org/vab",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Seminole County Value Adjustment Board",
    mailingAddressLine1: "301 N Park Ave",
    mailingAddressCity: "Sanford",
    mailingAddressState: "FL",
    mailingAddressZip: "32771",
    intakeEmail: "vab@seminoleclerk.org",
  },
  {
    state: "FL",
    countyName: "Collier County",
    countyCode: "12021",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.collierclerk.com/vab",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Collier County Value Adjustment Board",
    assessorPhone: "(239) 252-8399",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.collierclerk.com/vab",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Collier County Value Adjustment Board",
    mailingAddressLine1: "3315 Tamiami Trail E",
    mailingAddressCity: "Naples",
    mailingAddressState: "FL",
    mailingAddressZip: "34112",
    intakeEmail: "vab@collierclerk.com",
  },
  {
    state: "FL",
    countyName: "Marion County",
    countyCode: "12083",
    poaDeadlineDays: 25,
    proSeDeadlineDays: 25,
    hasOnlinePortal: 1,
    portalUrl: "https://www.marioncountyclerk.org/vab",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Marion County Value Adjustment Board",
    assessorPhone: "(352) 671-5600",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.marioncountyclerk.org/vab",
    formTemplateName: "Florida DR-486 VAB Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-15",
    filingWindowEnd: "09-18",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Marion County Value Adjustment Board",
    mailingAddressLine1: "110 NW 1st Ave",
    mailingAddressCity: "Ocala",
    mailingAddressState: "FL",
    mailingAddressZip: "34475",
    intakeEmail: "vab@marioncountyclerk.org",
  },

  // ─── CALIFORNIA (portal counties) ────────────────────────────────────────
  {
    state: "CA",
    countyName: "Los Angeles County",
    countyCode: "06037",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://assessoronline.lacounty.gov/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "LA County Assessor",
    assessorPhone: "(213) 974-3211",
    hearingFormat: "in-person",
    hearingScheduleDays: 180,
    requiresAttorney: 0,
    formTemplateUrl: "https://assessoronline.lacounty.gov/",
    formTemplateName: "LA County Assessment Appeal Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "11-30",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "LA County Assessment Appeals Board",
    mailingAddressLine1: "500 W Temple St, Room B-4",
    mailingAddressCity: "Los Angeles",
    mailingAddressState: "CA",
    mailingAddressZip: "90012",
    intakeEmail: "aab@bos.lacounty.gov",
  },
  {
    state: "CA",
    countyName: "San Diego County",
    countyCode: "06073",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sdcounty.ca.gov/assessor/appeal",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "San Diego County Assessor",
    assessorPhone: "(619) 236-3771",
    hearingFormat: "in-person",
    hearingScheduleDays: 180,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sdcounty.ca.gov/assessor/appeal",
    formTemplateName: "SD County Assessment Appeal Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "11-30",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "San Diego County Assessment Appeals Board",
    mailingAddressLine1: "1600 Pacific Hwy, Room 402",
    mailingAddressCity: "San Diego",
    mailingAddressState: "CA",
    mailingAddressZip: "92101",
    intakeEmail: "aab@sdcounty.ca.gov",
  },
  {
    state: "CA",
    countyName: "Orange County",
    countyCode: "06059",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.ocassessor.gov/appeal",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Orange County Assessor",
    assessorPhone: "(714) 834-2727",
    hearingFormat: "in-person",
    hearingScheduleDays: 180,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.ocassessor.gov/appeal",
    formTemplateName: "OC Assessment Appeal Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "11-30",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Orange County Assessment Appeals Board",
    mailingAddressLine1: "12 Civic Center Plaza, Room 101",
    mailingAddressCity: "Santa Ana",
    mailingAddressState: "CA",
    mailingAddressZip: "92701",
    intakeEmail: "aab@ocgov.com",
  },
  {
    state: "CA",
    countyName: "Riverside County",
    countyCode: "06065",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.assessor.co.riverside.ca.us/appeal",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Riverside County Assessor",
    assessorPhone: "(951) 955-6200",
    hearingFormat: "in-person",
    hearingScheduleDays: 180,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.assessor.co.riverside.ca.us/appeal",
    formTemplateName: "Riverside County Assessment Appeal Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "11-30",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Riverside County Assessment Appeals Board",
    mailingAddressLine1: "4080 Lemon St, 14th Floor",
    mailingAddressCity: "Riverside",
    mailingAddressState: "CA",
    mailingAddressZip: "92501",
    intakeEmail: "aab@rivco.org",
  },
  {
    state: "CA",
    countyName: "San Bernardino County",
    countyCode: "06071",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sbcounty.gov/assessor/appeal",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "San Bernardino County Assessor",
    assessorPhone: "(909) 387-8307",
    hearingFormat: "in-person",
    hearingScheduleDays: 180,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sbcounty.gov/assessor/appeal",
    formTemplateName: "SB County Assessment Appeal Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "11-30",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "San Bernardino County Assessment Appeals Board",
    mailingAddressLine1: "385 N Arrowhead Ave, 2nd Floor",
    mailingAddressCity: "San Bernardino",
    mailingAddressState: "CA",
    mailingAddressZip: "92415",
    intakeEmail: "aab@sbcounty.gov",
  },
  {
    state: "CA",
    countyName: "Alameda County",
    countyCode: "06001",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.acgov.org/assessor/appeal",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Alameda County Assessor",
    assessorPhone: "(510) 272-3787",
    hearingFormat: "in-person",
    hearingScheduleDays: 180,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.acgov.org/assessor/appeal",
    formTemplateName: "Alameda County Assessment Appeal Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Alameda County Assessment Appeals Board",
    mailingAddressLine1: "1221 Oak St, Room 536",
    mailingAddressCity: "Oakland",
    mailingAddressState: "CA",
    mailingAddressZip: "94612",
    intakeEmail: "aab@acgov.org",
  },
  {
    state: "CA",
    countyName: "Santa Clara County",
    countyCode: "06085",
    poaDeadlineDays: 60,
    proSeDeadlineDays: 60,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sccassessor.org/appeal",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Santa Clara County Assessor",
    assessorPhone: "(408) 299-5300",
    hearingFormat: "in-person",
    hearingScheduleDays: 180,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sccassessor.org/appeal",
    formTemplateName: "Santa Clara County Assessment Appeal Application",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-02",
    filingWindowEnd: "09-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Santa Clara County Assessment Appeals Board",
    mailingAddressLine1: "70 W Hedding St, East Wing, 10th Floor",
    mailingAddressCity: "San Jose",
    mailingAddressState: "CA",
    mailingAddressZip: "95110",
    intakeEmail: "aab@scc.gov",
  },

  // ─── NEW YORK (portal counties) ───────────────────────────────────────────
  {
    state: "NY",
    countyName: "Nassau County",
    countyCode: "36059",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.nassaucountyny.gov/agencies/assessor/appeal",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Nassau County Department of Assessment",
    assessorPhone: "(516) 571-1500",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.nassaucountyny.gov/agencies/assessor/appeal",
    formTemplateName: "Nassau County Assessment Review Commission",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-02",
    filingWindowEnd: "03-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Nassau County Assessment Review Commission",
    mailingAddressLine1: "240 Old Country Rd",
    mailingAddressCity: "Mineola",
    mailingAddressState: "NY",
    mailingAddressZip: "11501",
    intakeEmail: "arc@nassaucountyny.gov",
  },
  {
    state: "NY",
    countyName: "Suffolk County",
    countyCode: "36103",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.suffolkcountyny.gov/Departments/CountyClerk/Assessment-Review",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Suffolk County Assessment Review Commission",
    assessorPhone: "(631) 853-4800",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.suffolkcountyny.gov/Departments/CountyClerk/Assessment-Review",
    formTemplateName: "Suffolk County Assessment Review Commission",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Suffolk County Assessment Review Commission",
    mailingAddressLine1: "300 Center Dr",
    mailingAddressCity: "Riverhead",
    mailingAddressState: "NY",
    mailingAddressZip: "11901",
    intakeEmail: "arc@suffolkcountyny.gov",
  },
  {
    state: "NY",
    countyName: "Westchester County",
    countyCode: "36119",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://tax.westchestergov.com/",
    acceptsEmail: 0,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Westchester County Department of Finance",
    assessorPhone: "(914) 995-4325",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: 0,
    formTemplateUrl: "https://tax.westchestergov.com/",
    formTemplateName: "Westchester County Small Claims Assessment Review",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Westchester County Board of Assessment Review",
    mailingAddressLine1: "148 Martine Ave",
    mailingAddressCity: "White Plains",
    mailingAddressState: "NY",
    mailingAddressZip: "10601",
    intakeEmail: "taxappeal@westchestergov.com",
  },

  // ─── ILLINOIS (additional portal counties) ────────────────────────────────
  {
    state: "IL",
    countyName: "Kane County",
    countyCode: "17089",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.kanecountyassessor.com/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Kane County Supervisor of Assessments",
    assessorPhone: "(630) 208-3818",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.kanecountyassessor.com/appeal",
    formTemplateName: "Kane County Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "06-01",
    filingWindowEnd: "07-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Kane County Board of Review",
    mailingAddressLine1: "719 S Batavia Ave, Bldg B",
    mailingAddressCity: "Geneva",
    mailingAddressState: "IL",
    mailingAddressZip: "60134",
    intakeEmail: "boardofreview@co.kane.il.us",
  },
  {
    state: "IL",
    countyName: "McHenry County",
    countyCode: "17111",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.mchenrycountyil.gov/county-government/departments-j-z/supervisor-of-assessments/board-of-review",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "McHenry County Supervisor of Assessments",
    assessorPhone: "(815) 334-4290",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.mchenrycountyil.gov/county-government/departments-j-z/supervisor-of-assessments/board-of-review",
    formTemplateName: "McHenry County Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "06-01",
    filingWindowEnd: "07-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "McHenry County Board of Review",
    mailingAddressLine1: "667 Ware Rd",
    mailingAddressCity: "Woodstock",
    mailingAddressState: "IL",
    mailingAddressZip: "60098",
    intakeEmail: "boardofreview@co.mchenry.il.us",
  },

  // ─── OHIO (additional portal counties) ────────────────────────────────────
  {
    state: "OH",
    countyName: "Hamilton County",
    countyCode: "39061",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.hamiltoncountyauditor.org/BOR",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Hamilton County Auditor",
    assessorPhone: "(513) 946-4000",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.hamiltoncountyauditor.org/BOR",
    formTemplateName: "Hamilton County BOR Complaint",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "03-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Hamilton County Board of Revision",
    mailingAddressLine1: "138 E Court St, Room 304",
    mailingAddressCity: "Cincinnati",
    mailingAddressState: "OH",
    mailingAddressZip: "45202",
    intakeEmail: "bor@hamiltoncountyohio.gov",
  },
  {
    state: "OH",
    countyName: "Montgomery County",
    countyCode: "39113",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.mcohio.org/government/elected_officials/auditor/board_of_revision.php",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Montgomery County Auditor",
    assessorPhone: "(937) 225-4326",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.mcohio.org/government/elected_officials/auditor/board_of_revision.php",
    formTemplateName: "Montgomery County BOR Complaint",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "03-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Montgomery County Board of Revision",
    mailingAddressLine1: "451 W Third St",
    mailingAddressCity: "Dayton",
    mailingAddressState: "OH",
    mailingAddressZip: "45422",
    intakeEmail: "bor@mcohio.org",
  },
  {
    state: "OH",
    countyName: "Lucas County",
    countyCode: "39095",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.lucas.oh.us/index.aspx?NID=2079",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Lucas County Auditor",
    assessorPhone: "(419) 213-4406",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.lucas.oh.us/index.aspx?NID=2079",
    formTemplateName: "Lucas County BOR Complaint",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "03-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Lucas County Board of Revision",
    mailingAddressLine1: "One Government Center, Suite 500",
    mailingAddressCity: "Toledo",
    mailingAddressState: "OH",
    mailingAddressZip: "43604",
    intakeEmail: "bor@co.lucas.oh.us",
  },

  // ─── WASHINGTON (additional portal counties) ──────────────────────────────
  {
    state: "WA",
    countyName: "Clark County",
    countyCode: "53011",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.clark.wa.gov/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Clark County Assessor",
    assessorPhone: "(564) 397-2391",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.clark.wa.gov/assessor/appeal",
    formTemplateName: "Clark County Board of Equalization Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-01",
    filingWindowEnd: "07-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Clark County Board of Equalization",
    mailingAddressLine1: "1300 Franklin St",
    mailingAddressCity: "Vancouver",
    mailingAddressState: "WA",
    mailingAddressZip: "98660",
    intakeEmail: "boe@clark.wa.gov",
  },
  {
    state: "WA",
    countyName: "Spokane County",
    countyCode: "53063",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.spokanecounty.org/1101/Board-of-Equalization",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Spokane County Assessor",
    assessorPhone: "(509) 477-3698",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.spokanecounty.org/1101/Board-of-Equalization",
    formTemplateName: "Spokane County Board of Equalization Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-01",
    filingWindowEnd: "07-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Spokane County Board of Equalization",
    mailingAddressLine1: "1116 W Broadway Ave",
    mailingAddressCity: "Spokane",
    mailingAddressState: "WA",
    mailingAddressZip: "99260",
    intakeEmail: "boe@spokanecounty.org",
  },

  // ─── GEORGIA (additional portal counties) ─────────────────────────────────
  {
    state: "GA",
    countyName: "Cherokee County",
    countyCode: "13057",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.cherokeega.com/departments/tax-assessors/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Cherokee County Board of Tax Assessors",
    assessorPhone: "(678) 493-6120",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.cherokeega.com/departments/tax-assessors/appeal",
    formTemplateName: "Georgia PT-311A Appeal of Assessment",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Cherokee County Board of Tax Assessors",
    mailingAddressLine1: "110 Railroad St",
    mailingAddressCity: "Canton",
    mailingAddressState: "GA",
    mailingAddressZip: "30114",
    intakeEmail: "taxassessors@cherokeega.com",
  },
  {
    state: "GA",
    countyName: "Henry County",
    countyCode: "13151",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.henry.ga.us/departments/tax-assessors/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Henry County Board of Tax Assessors",
    assessorPhone: "(770) 288-7999",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.henry.ga.us/departments/tax-assessors/appeal",
    formTemplateName: "Georgia PT-311A Appeal of Assessment",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Henry County Board of Tax Assessors",
    mailingAddressLine1: "140 Henry Pkwy",
    mailingAddressCity: "McDonough",
    mailingAddressState: "GA",
    mailingAddressZip: "30253",
    intakeEmail: "taxassessors@co.henry.ga.us",
  },

  // ─── COLORADO (additional portal counties) ────────────────────────────────
  {
    state: "CO",
    countyName: "Adams County",
    countyCode: "08001",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.adcogov.org/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Adams County Assessor",
    assessorPhone: "(720) 523-6038",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.adcogov.org/assessor/appeal",
    formTemplateName: "Adams County Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Adams County Board of Equalization",
    mailingAddressLine1: "4430 S Adams County Pkwy",
    mailingAddressCity: "Brighton",
    mailingAddressState: "CO",
    mailingAddressZip: "80601",
    intakeEmail: "assessor@adcogov.org",
  },
  {
    state: "CO",
    countyName: "Boulder County",
    countyCode: "08013",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.bouldercounty.org/property-and-land/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Boulder County Assessor",
    assessorPhone: "(303) 441-3530",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.bouldercounty.org/property-and-land/assessor/appeal",
    formTemplateName: "Boulder County Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Boulder County Board of Equalization",
    mailingAddressLine1: "1325 Pearl St",
    mailingAddressCity: "Boulder",
    mailingAddressState: "CO",
    mailingAddressZip: "80302",
    intakeEmail: "assessor@bouldercounty.org",
  },
  {
    state: "CO",
    countyName: "Larimer County",
    countyCode: "08069",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.larimer.gov/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Larimer County Assessor",
    assessorPhone: "(970) 498-7050",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.larimer.gov/assessor/appeal",
    formTemplateName: "Larimer County Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Larimer County Board of Equalization",
    mailingAddressLine1: "200 W Oak St",
    mailingAddressCity: "Fort Collins",
    mailingAddressState: "CO",
    mailingAddressZip: "80521",
    intakeEmail: "assessor@larimer.gov",
  },

  // ─── MINNESOTA (portal counties) ──────────────────────────────────────────
  {
    state: "MN",
    countyName: "Anoka County",
    countyCode: "27003",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.anokacounty.us/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Anoka County Assessor",
    assessorPhone: "(763) 323-5400",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.anokacounty.us/assessor/appeal",
    formTemplateName: "Minnesota Property Tax Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "04-30",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Anoka County Board of Appeal and Equalization",
    mailingAddressLine1: "2100 3rd Ave",
    mailingAddressCity: "Anoka",
    mailingAddressState: "MN",
    mailingAddressZip: "55303",
    intakeEmail: "assessor@co.anoka.mn.us",
  },
  {
    state: "MN",
    countyName: "Washington County",
    countyCode: "27163",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.washington.mn.us/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Washington County Assessor",
    assessorPhone: "(651) 430-6175",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.washington.mn.us/assessor/appeal",
    formTemplateName: "Minnesota Property Tax Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "04-30",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Washington County Board of Appeal and Equalization",
    mailingAddressLine1: "14949 62nd St N",
    mailingAddressCity: "Stillwater",
    mailingAddressState: "MN",
    mailingAddressZip: "55082",
    intakeEmail: "assessor@co.washington.mn.us",
  },

  // ─── MICHIGAN (portal counties) ───────────────────────────────────────────
  {
    state: "MI",
    countyName: "Kent County",
    countyCode: "26081",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.accesskent.com/Departments/Equalization/appeal.htm",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Kent County Equalization Department",
    assessorPhone: "(616) 632-7500",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.accesskent.com/Departments/Equalization/appeal.htm",
    formTemplateName: "Michigan Tax Tribunal Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-01",
    filingWindowEnd: "03-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Kent County Board of Review",
    mailingAddressLine1: "300 Monroe Ave NW",
    mailingAddressCity: "Grand Rapids",
    mailingAddressState: "MI",
    mailingAddressZip: "49503",
    intakeEmail: "equalization@kentcountymi.gov",
  },
  {
    state: "MI",
    countyName: "Washtenaw County",
    countyCode: "26161",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.washtenaw.org/government/departments/equalization/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Washtenaw County Equalization Department",
    assessorPhone: "(734) 222-6780",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.washtenaw.org/government/departments/equalization/appeal",
    formTemplateName: "Michigan Tax Tribunal Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-01",
    filingWindowEnd: "03-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Washtenaw County Board of Review",
    mailingAddressLine1: "200 N Main St",
    mailingAddressCity: "Ann Arbor",
    mailingAddressState: "MI",
    mailingAddressZip: "48104",
    intakeEmail: "equalization@washtenaw.org",
  },

  // ─── NORTH CAROLINA (portal counties) ─────────────────────────────────────
  {
    state: "NC",
    countyName: "Forsyth County",
    countyCode: "37067",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.forsyth.cc/tax/appeal.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Forsyth County Tax Assessor",
    assessorPhone: "(336) 703-2300",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.forsyth.cc/tax/appeal.aspx",
    formTemplateName: "NC Board of Equalization and Review Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Forsyth County Board of Equalization and Review",
    mailingAddressLine1: "201 N Chestnut St",
    mailingAddressCity: "Winston-Salem",
    mailingAddressState: "NC",
    mailingAddressZip: "27101",
    intakeEmail: "taxappeal@forsyth.cc",
  },
  {
    state: "NC",
    countyName: "Durham County",
    countyCode: "37063",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.dconc.gov/government/departments-f-z/tax-administration/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Durham County Tax Assessor",
    assessorPhone: "(919) 560-0300",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.dconc.gov/government/departments-f-z/tax-administration/appeal",
    formTemplateName: "NC Board of Equalization and Review Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "04-01",
    filingWindowEnd: "05-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Durham County Board of Equalization and Review",
    mailingAddressLine1: "201 E Main St",
    mailingAddressCity: "Durham",
    mailingAddressState: "NC",
    mailingAddressZip: "27701",
    intakeEmail: "taxappeal@dconc.gov",
  },

  // ─── VIRGINIA (portal counties) ───────────────────────────────────────────
  {
    state: "VA",
    countyName: "Loudoun County",
    countyCode: "51107",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.loudoun.gov/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Loudoun County Commissioner of the Revenue",
    assessorPhone: "(703) 777-0260",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.loudoun.gov/assessor/appeal",
    formTemplateName: "Virginia Board of Equalization Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-01",
    filingWindowEnd: "04-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Loudoun County Board of Equalization",
    mailingAddressLine1: "1 Harrison St SE",
    mailingAddressCity: "Leesburg",
    mailingAddressState: "VA",
    mailingAddressZip: "20175",
    intakeEmail: "assessor@loudoun.gov",
  },
  {
    state: "VA",
    countyName: "Chesterfield County",
    countyCode: "51041",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.chesterfield.gov/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Chesterfield County Real Estate Assessor",
    assessorPhone: "(804) 748-1321",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.chesterfield.gov/assessor/appeal",
    formTemplateName: "Virginia Board of Equalization Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "02-01",
    filingWindowEnd: "04-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Chesterfield County Board of Equalization",
    mailingAddressLine1: "9901 Lori Rd",
    mailingAddressCity: "Chesterfield",
    mailingAddressState: "VA",
    mailingAddressZip: "23832",
    intakeEmail: "assessor@chesterfield.gov",
  },

  // ─── MARYLAND (portal counties) ───────────────────────────────────────────
  {
    state: "MD",
    countyName: "Anne Arundel County",
    countyCode: "24003",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Maryland SDAT — Anne Arundel",
    assessorPhone: "(410) 974-5709",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    formTemplateName: "Maryland Property Tax Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "02-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Maryland State Department of Assessments and Taxation",
    mailingAddressLine1: "44 Calvert St",
    mailingAddressCity: "Annapolis",
    mailingAddressState: "MD",
    mailingAddressZip: "21401",
    intakeEmail: "sdat.realpropertyappeal@maryland.gov",
  },
  {
    state: "MD",
    countyName: "Howard County",
    countyCode: "24027",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Maryland SDAT — Howard County",
    assessorPhone: "(410) 480-7940",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    formTemplateName: "Maryland Property Tax Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "02-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Maryland State Department of Assessments and Taxation",
    mailingAddressLine1: "3430 Court House Dr",
    mailingAddressCity: "Ellicott City",
    mailingAddressState: "MD",
    mailingAddressZip: "21043",
    intakeEmail: "sdat.realpropertyappeal@maryland.gov",
  },

  // ─── TENNESSEE (portal counties) ──────────────────────────────────────────
  {
    state: "TN",
    countyName: "Shelby County",
    countyCode: "47157",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.assessormelissa.com/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Shelby County Assessor of Property",
    assessorPhone: "(901) 222-7001",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.assessormelissa.com/appeal",
    formTemplateName: "Tennessee Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Shelby County Board of Equalization",
    mailingAddressLine1: "1075 Mullins Station Rd",
    mailingAddressCity: "Memphis",
    mailingAddressState: "TN",
    mailingAddressZip: "38134",
    intakeEmail: "assessor@shelbycountytn.gov",
  },
  {
    state: "TN",
    countyName: "Davidson County",
    countyCode: "47037",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.padctn.org/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Davidson County Assessor of Property",
    assessorPhone: "(615) 862-6080",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.padctn.org/appeal",
    formTemplateName: "Tennessee Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Davidson County Board of Equalization",
    mailingAddressLine1: "700 2nd Ave S",
    mailingAddressCity: "Nashville",
    mailingAddressState: "TN",
    mailingAddressZip: "37210",
    intakeEmail: "assessor@nashville.gov",
  },
  {
    state: "TN",
    countyName: "Knox County",
    countyCode: "47093",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.knoxcounty.org/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Knox County Property Assessor",
    assessorPhone: "(865) 215-2360",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.knoxcounty.org/assessor/appeal",
    formTemplateName: "Tennessee Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "06-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Knox County Board of Equalization",
    mailingAddressLine1: "400 Main Ave SW",
    mailingAddressCity: "Knoxville",
    mailingAddressState: "TN",
    mailingAddressZip: "37902",
    intakeEmail: "assessor@knoxcounty.org",
  },

  // ─── NEVADA (portal counties) ─────────────────────────────────────────────
  {
    state: "NV",
    countyName: "Clark County",
    countyCode: "32003",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.clarkcountynv.gov/government/departments/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Clark County Assessor",
    assessorPhone: "(702) 455-3882",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.clarkcountynv.gov/government/departments/assessor/appeal",
    formTemplateName: "Nevada Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "01-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Clark County Board of Equalization",
    mailingAddressLine1: "500 S Grand Central Pkwy",
    mailingAddressCity: "Las Vegas",
    mailingAddressState: "NV",
    mailingAddressZip: "89155",
    intakeEmail: "assessor@clarkcountynv.gov",
  },
  {
    state: "NV",
    countyName: "Washoe County",
    countyCode: "32031",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.washoecounty.gov/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Washoe County Assessor",
    assessorPhone: "(775) 328-2277",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.washoecounty.gov/assessor/appeal",
    formTemplateName: "Nevada Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "01-01",
    filingWindowEnd: "01-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Washoe County Board of Equalization",
    mailingAddressLine1: "1001 E 9th St",
    mailingAddressCity: "Reno",
    mailingAddressState: "NV",
    mailingAddressZip: "89512",
    intakeEmail: "assessor@washoecounty.gov",
  },

  // ─── OREGON (portal counties) ─────────────────────────────────────────────
  {
    state: "OR",
    countyName: "Multnomah County",
    countyCode: "41051",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.multco.us/assessment-taxation/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Multnomah County Assessment and Taxation",
    assessorPhone: "(503) 988-3326",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.multco.us/assessment-taxation/appeal",
    formTemplateName: "Oregon Magistrate Division Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "10-01",
    filingWindowEnd: "12-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Multnomah County Board of Property Tax Appeals",
    mailingAddressLine1: "501 SE Hawthorne Blvd",
    mailingAddressCity: "Portland",
    mailingAddressState: "OR",
    mailingAddressZip: "97214",
    intakeEmail: "assessment.taxation@multco.us",
  },
  {
    state: "OR",
    countyName: "Washington County",
    countyCode: "41067",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.washington.or.us/AssessmentTaxation/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Washington County Assessment and Taxation",
    assessorPhone: "(503) 846-8741",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.washington.or.us/AssessmentTaxation/appeal",
    formTemplateName: "Oregon Magistrate Division Petition",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "10-01",
    filingWindowEnd: "12-31",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Washington County Board of Property Tax Appeals",
    mailingAddressLine1: "155 N First Ave",
    mailingAddressCity: "Hillsboro",
    mailingAddressState: "OR",
    mailingAddressZip: "97124",
    intakeEmail: "assessment@co.washington.or.us",
  },

  // ─── UTAH (portal counties) ───────────────────────────────────────────────
  {
    state: "UT",
    countyName: "Salt Lake County",
    countyCode: "49035",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://slco.org/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Salt Lake County Assessor",
    assessorPhone: "(385) 468-8000",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://slco.org/assessor/appeal",
    formTemplateName: "Utah County Board of Equalization Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "09-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Salt Lake County Board of Equalization",
    mailingAddressLine1: "2001 S State St",
    mailingAddressCity: "Salt Lake City",
    mailingAddressState: "UT",
    mailingAddressZip: "84190",
    intakeEmail: "assessor@slco.org",
  },
  {
    state: "UT",
    countyName: "Utah County",
    countyCode: "49049",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.utahcounty.gov/Dept/Assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Utah County Assessor",
    assessorPhone: "(801) 851-8244",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.utahcounty.gov/Dept/Assessor/appeal",
    formTemplateName: "Utah County Board of Equalization Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-01",
    filingWindowEnd: "09-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Utah County Board of Equalization",
    mailingAddressLine1: "100 E Center St",
    mailingAddressCity: "Provo",
    mailingAddressState: "UT",
    mailingAddressZip: "84606",
    intakeEmail: "assessor@utahcounty.gov",
  },

  // ─── PENNSYLVANIA (additional portal counties) ────────────────────────────
  {
    state: "PA",
    countyName: "Chester County",
    countyCode: "42029",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.chesco.org/assessments/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Chester County Board of Assessment Appeals",
    assessorPhone: "(610) 344-6105",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.chesco.org/assessments/appeal",
    formTemplateName: "Pennsylvania Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-01",
    filingWindowEnd: "09-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Chester County Board of Assessment Appeals",
    mailingAddressLine1: "313 W Market St",
    mailingAddressCity: "West Chester",
    mailingAddressState: "PA",
    mailingAddressZip: "19380",
    intakeEmail: "assessments@chesco.org",
  },
  {
    state: "PA",
    countyName: "Delaware County",
    countyCode: "42045",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.co.delaware.pa.us/assessments/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Delaware County Board of Assessment Appeals",
    assessorPhone: "(610) 891-4893",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.co.delaware.pa.us/assessments/appeal",
    formTemplateName: "Pennsylvania Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "08-01",
    filingWindowEnd: "09-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Delaware County Board of Assessment Appeals",
    mailingAddressLine1: "201 W Front St",
    mailingAddressCity: "Media",
    mailingAddressState: "PA",
    mailingAddressZip: "19063",
    intakeEmail: "assessments@co.delaware.pa.us",
  },

  // ─── ARIZONA (additional portal counties) ─────────────────────────────────
  {
    state: "AZ",
    countyName: "Pinal County",
    countyCode: "04021",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.pinalcountyaz.gov/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Pinal County Assessor",
    assessorPhone: "(520) 866-6361",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.pinalcountyaz.gov/assessor/appeal",
    formTemplateName: "Arizona Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "11-01",
    filingWindowEnd: "12-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Pinal County Board of Supervisors",
    mailingAddressLine1: "31 N Pinal St",
    mailingAddressCity: "Florence",
    mailingAddressState: "AZ",
    mailingAddressZip: "85132",
    intakeEmail: "assessor@pinalcountyaz.gov",
  },
  {
    state: "AZ",
    countyName: "Yavapai County",
    countyCode: "04025",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.yavapai.us/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Yavapai County Assessor",
    assessorPhone: "(928) 771-3220",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.yavapai.us/assessor/appeal",
    formTemplateName: "Arizona Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "11-01",
    filingWindowEnd: "12-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Yavapai County Board of Supervisors",
    mailingAddressLine1: "1015 Fair St",
    mailingAddressCity: "Prescott",
    mailingAddressState: "AZ",
    mailingAddressZip: "86305",
    intakeEmail: "assessor@yavapai.us",
  },

  // ─── SOUTH CAROLINA (portal counties) ─────────────────────────────────────
  {
    state: "SC",
    countyName: "Greenville County",
    countyCode: "45045",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.greenvillecounty.org/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Greenville County Assessor",
    assessorPhone: "(864) 467-7300",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.greenvillecounty.org/assessor/appeal",
    formTemplateName: "South Carolina Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-01",
    filingWindowEnd: "08-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Greenville County Board of Assessment Appeals",
    mailingAddressLine1: "301 University Ridge",
    mailingAddressCity: "Greenville",
    mailingAddressState: "SC",
    mailingAddressZip: "29601",
    intakeEmail: "assessor@greenvillecounty.org",
  },
  {
    state: "SC",
    countyName: "Richland County",
    countyCode: "45079",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.richlandcountysc.gov/Departments/Assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Richland County Assessor",
    assessorPhone: "(803) 576-2640",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.richlandcountysc.gov/Departments/Assessor/appeal",
    formTemplateName: "South Carolina Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "07-01",
    filingWindowEnd: "08-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Richland County Board of Assessment Appeals",
    mailingAddressLine1: "2020 Hampton St",
    mailingAddressCity: "Columbia",
    mailingAddressState: "SC",
    mailingAddressZip: "29204",
    intakeEmail: "assessor@richlandcountysc.gov",
  },

  // ─── INDIANA (portal counties) ────────────────────────────────────────────
  {
    state: "IN",
    countyName: "Marion County",
    countyCode: "18097",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.indy.gov/activity/file-a-property-tax-appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Marion County Assessor",
    assessorPhone: "(317) 327-4907",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.indy.gov/activity/file-a-property-tax-appeal",
    formTemplateName: "Indiana Property Tax Appeal Form 130",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-10",
    filingWindowEnd: "06-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Marion County Property Tax Assessment Board of Appeals",
    mailingAddressLine1: "200 E Washington St",
    mailingAddressCity: "Indianapolis",
    mailingAddressState: "IN",
    mailingAddressZip: "46204",
    intakeEmail: "assessor@indy.gov",
  },
  {
    state: "IN",
    countyName: "Hamilton County",
    countyCode: "18057",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.hamiltoncounty.in.gov/assessor/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Hamilton County Assessor",
    assessorPhone: "(317) 776-9617",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.hamiltoncounty.in.gov/assessor/appeal",
    formTemplateName: "Indiana Property Tax Appeal Form 130",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "05-10",
    filingWindowEnd: "06-15",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Hamilton County Property Tax Assessment Board of Appeals",
    mailingAddressLine1: "One Hamilton County Square",
    mailingAddressCity: "Noblesville",
    mailingAddressState: "IN",
    mailingAddressZip: "46060",
    intakeEmail: "assessor@hamiltoncounty.in.gov",
  },

  // ─── KANSAS (portal counties) ─────────────────────────────────────────────
  {
    state: "KS",
    countyName: "Johnson County",
    countyCode: "20091",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.jocogov.org/dept/appraiser/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Johnson County Appraiser",
    assessorPhone: "(913) 715-9000",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.jocogov.org/dept/appraiser/appeal",
    formTemplateName: "Kansas Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "03-01",
    filingWindowEnd: "04-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Johnson County Board of Tax Appeals",
    mailingAddressLine1: "111 S Cherry St",
    mailingAddressCity: "Olathe",
    mailingAddressState: "KS",
    mailingAddressZip: "66061",
    intakeEmail: "appraiser@jocogov.org",
  },
  {
    state: "KS",
    countyName: "Sedgwick County",
    countyCode: "20173",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: 1,
    portalUrl: "https://www.sedgwickcounty.org/appraiser/appeal",
    acceptsEmail: 1,
    acceptsMail: 1,
    acceptsInPerson: 1,
    assessorName: "Sedgwick County Appraiser",
    assessorPhone: "(316) 660-9000",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: 0,
    formTemplateUrl: "https://www.sedgwickcounty.org/appraiser/appeal",
    formTemplateName: "Kansas Assessment Appeal",
    poaEligible: 1,
    onlinePortalOnly: 0,
    pinOnlyLogin: 0,
    filingWindowStart: "03-01",
    filingWindowEnd: "04-01",
    preferredChannel: "portal",
    fallbackChannel: "mail_certified",
    mailingAddressName: "Sedgwick County Board of Tax Appeals",
    mailingAddressLine1: "525 N Main St",
    mailingAddressCity: "Wichita",
    mailingAddressState: "KS",
    mailingAddressZip: "67203",
    intakeEmail: "appraiser@sedgwickcounty.org",
  },
];
