/**
 * County Data Seed
 * Populates counties table with filing information for 10 high-impact states
 * States: TX, IL, NJ, CT, WI, OH, PA, CA, NY, FL
 */

export const COUNTY_SEED_DATA = [
  // TEXAS (2.4% avg tax rate)
  {
    state: "TX",
    countyName: "Travis County",
    countyCode: "48453",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://traviscad.org/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Travis Central Appraisal District",
    assessorPhone: "(512) 834-9100",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: false,
    formTemplateUrl: "https://traviscad.org/forms/",
    formTemplateName: "Travis County ARB Appeal Form",
  },
  {
    state: "TX",
    countyName: "Dallas County",
    countyCode: "48113",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www.dallascad.org/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Dallas Central Appraisal District",
    assessorPhone: "(214) 631-0000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: false,
    formTemplateUrl: "https://www.dallascad.org/forms/",
    formTemplateName: "Dallas County ARB Appeal Form",
  },
  {
    state: "TX",
    countyName: "Harris County",
    countyCode: "48201",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www.hcad.org/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Harris County Appraisal District",
    assessorPhone: "(713) 207-3000",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: false,
    formTemplateUrl: "https://www.hcad.org/forms/",
    formTemplateName: "Harris County ARB Appeal Form",
  },

  // ILLINOIS (2.2% avg tax rate)
  {
    state: "IL",
    countyName: "Cook County",
    countyCode: "17031",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www.cookcountyassessor.com/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Cook County Assessor",
    assessorPhone: "(312) 443-7550",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: false,
    formTemplateUrl: "https://www.cookcountyassessor.com/forms/",
    formTemplateName: "Cook County Assessment Appeal Form",
  },
  {
    state: "IL",
    countyName: "DuPage County",
    countyCode: "17043",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www.dupagecountyassessor.com/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "DuPage County Assessor",
    assessorPhone: "(630) 407-6500",
    hearingFormat: "hybrid",
    hearingScheduleDays: 45,
    requiresAttorney: false,
    formTemplateUrl: "https://www.dupagecountyassessor.com/forms/",
    formTemplateName: "DuPage County Assessment Appeal Form",
  },

  // NEW JERSEY (2.1% avg tax rate)
  {
    state: "NJ",
    countyName: "Bergen County",
    countyCode: "34003",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: true,
    portalUrl: "https://www.bergencountynj.gov/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Bergen County Tax Board",
    assessorPhone: "(201) 336-6400",
    hearingFormat: "in-person",
    hearingScheduleDays: 60,
    requiresAttorney: false,
    formTemplateUrl: "https://www.bergencountynj.gov/forms/",
    formTemplateName: "Bergen County Tax Appeal Form",
  },
  {
    state: "NJ",
    countyName: "Essex County",
    countyCode: "34013",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: true,
    portalUrl: "https://www.essexcountynj.org/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Essex County Tax Board",
    assessorPhone: "(973) 621-4500",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: false,
    formTemplateUrl: "https://www.essexcountynj.org/forms/",
    formTemplateName: "Essex County Tax Appeal Form",
  },

  // CONNECTICUT (2.0% avg tax rate)
  {
    state: "CT",
    countyName: "Fairfield County",
    countyCode: "09001",
    poaDeadlineDays: 45,
    proSeDeadlineDays: 45,
    hasOnlinePortal: true,
    portalUrl: "https://portal.ct.gov/OPM/Property-Valuation-Appeals-Board/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "CT Property Valuation Appeals Board",
    assessorPhone: "(860) 702-3000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 90,
    requiresAttorney: false,
    formTemplateUrl: "https://portal.ct.gov/OPM/forms/",
    formTemplateName: "Connecticut Property Appeal Form",
  },

  // WISCONSIN (1.8% avg tax rate)
  {
    state: "WI",
    countyName: "Milwaukee County",
    countyCode: "55079",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://county.milwaukee.gov/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Milwaukee County Assessor",
    assessorPhone: "(414) 278-4455",
    hearingFormat: "in-person",
    hearingScheduleDays: 45,
    requiresAttorney: false,
    formTemplateUrl: "https://county.milwaukee.gov/forms/",
    formTemplateName: "Milwaukee County Assessment Appeal Form",
  },

  // OHIO (1.5% avg tax rate)
  {
    state: "OH",
    countyName: "Cuyahoga County",
    countyCode: "39035",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www.cuyahogacounty.us/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Cuyahoga County Auditor",
    assessorPhone: "(216) 443-7000",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: false,
    formTemplateUrl: "https://www.cuyahogacounty.us/forms/",
    formTemplateName: "Cuyahoga County Property Tax Appeal Form",
  },

  // PENNSYLVANIA (1.5% avg tax rate)
  {
    state: "PA",
    countyName: "Philadelphia County",
    countyCode: "42101",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www.phila.gov/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Philadelphia Board of Revision of Taxes",
    assessorPhone: "(215) 686-6600",
    hearingFormat: "in-person",
    hearingScheduleDays: 90,
    requiresAttorney: false,
    formTemplateUrl: "https://www.phila.gov/forms/",
    formTemplateName: "Philadelphia Property Tax Appeal Form",
  },

  // CALIFORNIA (0.8% but high values)
  {
    state: "CA",
    countyName: "Los Angeles County",
    countyCode: "06037",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://assessor.lacounty.gov/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Los Angeles County Assessor",
    assessorPhone: "(213) 974-3211",
    hearingFormat: "virtual",
    hearingScheduleDays: 60,
    requiresAttorney: false,
    formTemplateUrl: "https://assessor.lacounty.gov/forms/",
    formTemplateName: "LA County Proposition 8 Application",
  },

  // NEW YORK (1.8% avg)
  {
    state: "NY",
    countyName: "New York County",
    countyCode: "36061",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www1.nyc.gov/site/finance/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "NYC Department of Finance",
    assessorPhone: "(311)",
    hearingFormat: "hybrid",
    hearingScheduleDays: 60,
    requiresAttorney: false,
    formTemplateUrl: "https://www1.nyc.gov/site/finance/forms/",
    formTemplateName: "NYC Property Tax Appeal Form",
  },

  // FLORIDA (0.8% but high volume)
  {
    state: "FL",
    countyName: "Miami-Dade County",
    countyCode: "12086",
    poaDeadlineDays: 30,
    proSeDeadlineDays: 30,
    hasOnlinePortal: true,
    portalUrl: "https://www.miamidade.gov/",
    acceptsEmail: true,
    acceptsMail: true,
    acceptsInPerson: true,
    assessorName: "Miami-Dade County Property Appraiser",
    assessorPhone: "(305) 375-2905",
    hearingFormat: "virtual",
    hearingScheduleDays: 45,
    requiresAttorney: false,
    formTemplateUrl: "https://www.miamidade.gov/forms/",
    formTemplateName: "Miami-Dade County Property Tax Appeal Form",
  },
];
