/**
 * Illinois Counties Backfill
 * All Illinois counties assess at 33.33% of market value (state-mandated)
 * This backfill adds the major Illinois counties with correct assessment rates and appeal deadlines
 */

export const ILLINOIS_COUNTIES_BACKFILL = [
  // Cook County (already exists, but included for reference)
  {
    state: "IL",
    county: "Cook",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.cookcountyassessor.com/",
    onlineFilingAvailable: true,
    successRate: 0.40,
    notes: "Chicago market. Strong appeal culture. Board of Review handles appeals.",
  },
  // Collar Counties
  {
    state: "IL",
    county: "DuPage",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.dupageco.org/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.38,
    notes: "Collar county. Suburban Chicago market.",
  },
  {
    state: "IL",
    county: "Lake",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.lakecountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.37,
    notes: "Collar county. Suburban Chicago market.",
  },
  {
    state: "IL",
    county: "Will",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.willcountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.36,
    notes: "Collar county. Suburban Chicago market.",
  },
  {
    state: "IL",
    county: "Kane",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.kanecountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.35,
    notes: "Collar county. Aurora market.",
  },
  {
    state: "IL",
    county: "McHenry",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.mchenrycountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.34,
    notes: "Collar county. Suburban Chicago market.",
  },
  // Major Downstate Counties
  {
    state: "IL",
    county: "Champaign",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.champaigncounty.org/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.32,
    notes: "University of Illinois market. Urbana-Champaign.",
  },
  {
    state: "IL",
    county: "Madison",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.madisoncountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.33,
    notes: "St. Louis metro area. Southwestern Illinois.",
  },
  {
    state: "IL",
    county: "St. Clair",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.stclaircountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.32,
    notes: "St. Louis metro area. Southwestern Illinois.",
  },
  {
    state: "IL",
    county: "Peoria",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.peoriacounty.org/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.31,
    notes: "Central Illinois. Peoria market.",
  },
  {
    state: "IL",
    county: "Sangamon",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.sangamoncounty.org/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.30,
    notes: "Central Illinois. Springfield (state capital).",
  },
  {
    state: "IL",
    county: "Winnebago",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.winnebagocounty.org/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.29,
    notes: "Northern Illinois. Rockford market.",
  },
  {
    state: "IL",
    county: "Dupage",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.dupageco.org/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.38,
    notes: "Collar county. Suburban Chicago market.",
  },
  {
    state: "IL",
    county: "Henry",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.henrycountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.28,
    notes: "Northwestern Illinois. Rock Island County area.",
  },
  {
    state: "IL",
    county: "Rock Island",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.rockislandcounty.org/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.27,
    notes: "Northwestern Illinois. Quad Cities market.",
  },
  {
    state: "IL",
    county: "McLean",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.mcleancountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.29,
    notes: "Central Illinois. Bloomington-Normal market.",
  },
  {
    state: "IL",
    county: "Tazewell",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.tazewell.com/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.28,
    notes: "Central Illinois. Peoria area.",
  },
  {
    state: "IL",
    county: "Will",
    assessmentRate: 33.33,
    appealDeadlineDays: 30,
    filingMethods: ["automated_standard", "pro_se"],
    onlinePortalUrl: "https://www.willcountyil.gov/assessor/",
    onlineFilingAvailable: true,
    successRate: 0.36,
    notes: "Collar county. Suburban Chicago market.",
  },
];
